INSERT INTO estadosOP (estado, vista_gerencia, grupo_gestion, proceso, vista_direccion) VALUES
('Pendiente generar IP MADRE','Nuevo Ingreso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Sin orden de compra','Nuevo Ingreso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('En proceso de Diseño','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño pendiente - IP MADRE sin orden de compra','Nuevo Ingreso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño pendiente - Entidad no envia documentos/planos actualizados','Entidad no envia documentos/planos actualizados','SIN RTPA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Diseño pendiente por falta de visita técnica - Pendiente de validar fecha por Entidad','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño pendiente - Diseño conceptual en proceso de revisión por la Entidad','Diseño conceptual en proceso de revisión por la Entidad','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño pendiente por no acceso a la zona de proyecto','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño Ejecutado, pdte Elab. Ppto','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('En proceso de Elab. Ppto','En proceso de Elab. Ppto','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Ppto enviado, pdte confirmacion de Entidad','Ppto enviado, pdte confirmacion de Entidad','EN COORDINACIÓN','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Ppto enviado, pdte confirmacion de Entidad (Anteproyecto)','Ppto enviado, pdte confirmacion de Entidad (Anteproyecto)','ANTEPROYECTO','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Ppto enviado, en proceso elab. Convenio','En gestión convenio','EN COORDINACIÓN','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Ppto con observaciones (a solicitud de la entidad)','En proceso de Elab. Ppto','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Ppto y Convenio enviados, pdte confirmacion Entidad','Ppto y Convenio enviados, pdte confirmacion Entidad','EN COORDINACIÓN','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Convenio en proceso de firma','En gestión convenio','EN COORDINACIÓN','2. EN GESTION DE CONVENIO','2. EN COORDINACION'),
('Convenio listo para la emision de factura','En gestión convenio','EN COORDINACIÓN','2. EN GESTION DE CONVENIO','2. EN COORDINACION'),
('Convenio con factura emitida, en proceso de pago','En proceso de Pago','EN COORDINACIÓN','1. GESTION DE PAGO','2. EN COORDINACION'),
('Convenio pdte de aceptación por la entidad','En gestión convenio','EN COORDINACIÓN','2. EN GESTION DE CONVENIO','2. EN COORDINACION'),
('Se modifica el alcance (En elab. De Nvo Diseño - Presupuesto)','Se modifica el alcance (En elab. De Nvo Diseño - Presupuesto)','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Cambio Gestión - Proyecto transferido a otra Entidad','Cambio Gestión - Proyecto transferido a otra Entidad','SIN RTPA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Diseño con observación interna','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Diseño con observación del cliente','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Entidad No acepta ppto, con observacion','Entidad No acepta ppto, con observacion','LA ENTIDAD NO ACEPTA EL PRESUPUESTO','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Entidad No acepta convenio, con observacion','Entidad No acepta convenio, con observacion','LA ENTIDAD NO ACEPTA EL PRESUPUESTO','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Cambio el alcance del proyecto, pdte información de Entidad','Cambio el alcance del proyecto, pdte información de Entidad','SIN RTPA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Cambio el alcance del proyecto, pdte diseño','En proceso','EN COORDINACIÓN','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Cambio el alcance del proyecto, pdte actualización del ppto','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Ya no existe interferencia','Ya no existe interferencia /No existe red de telefónica en ámbito del proyecto','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Cancelado, no existe interferencia en ámbito del proyecto','Ya no existe interferencia /No existe red de telefónica en ámbito del proyecto','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Desestimado, en gestión con otro código de OP','Desestimado, en gestión con otro código de OP','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Derivar a relaciones institucionales','Derivar a relaciones institucionales','LA ENTIDAD NO ACEPTA EL PRESUPUESTO','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Entidad acepta ppto, pndt. envío de info. por Diseño','Entidad acepta ppto, pndt. envío de info. por Diseño','EN COORDINACIÓN','3. EN GESTION PRESUPUESTO','2. EN COORDINACION'),
('Diseño con reparos','Cliente no ha formalizado carta de pedido','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Solo pedido de Información de Red','Cliente no ha formalizado carta de pedido','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Cliente no ha formalizado carta de pedido','Cliente no ha formalizado carta de pedido','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('No existe red de telefónica en ámbito del proyecto','Ya no existe interferencia /No existe red de telefónica en ámbito del proyecto','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('No acepta presupuesto - convenio','No acepta presupuesto - convenio','SIN RTPA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Pagado Abril 2023','Pagado Abril 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Anulado a pedido del cliente','Anulado a pedido del cliente','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Ejecutado por mantenimiento','Ejecutado por mantenimiento','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Con OC, sin acceso a zona de trabajo','Con OC, sin acceso a zona de trabajo','PARALIZADO','6. PARALIZADO','4. PARALIZADO'),
('Cambio de alcance, atendido con otro OP','Cambio de alcance, atendido con otro OP','DESESTIMADO','5. DESESTIMADO','0. DESESTIMADO'),
('Pagado Mayo 2023','Pagado Mayo 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('No acepta ppto (Pdte Elab cronologia para transf RRII)','No acepta ppto (Pdte Elab cronologia para transf RRII)','LA ENTIDAD NO ACEPTA EL PRESUPUESTO','4. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN','3. SIN RPTA DE LA ENTIDAD, EN COORDINACIÓN CON EQ. REGULACIÓN'),
('Pagado Junio 2023','Pagado Junio 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Ppto elaborado, pendiente de envío a la Entidad','En proceso','PREVIO AL PRESUPUESTO','3. EN GESTION PRESUPUESTO','4. EN GESTION PRESUPUESTO'),
('Pagado Julio 2023','Pagado Julio 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Pagado Agosto 2023','Pagado Agosto 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Pagado Setiembre 2023','Pagado Setiembre 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Pagado Octubre 2023','Pagado Octubre 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Pagado Febrero 2023','Pagado Febrero 2023','FACTURADO','6. FACTURADO','1. FACTURADO'),
('Pagado Noviembre 2023','Pagado Noviembre 2023','FACTURADO','6. FACTURADO','1. FACTURADO');