INSERT INTO distritos (departamento, provincia, distrito) VALUES
('Amazonas', 'Chachapoyas', 'Chachapoyas'),
('Amazonas', 'Chachapoyas', 'Asunción'),
('Amazonas', 'Chachapoyas', 'Balsas'),
('Amazonas', 'Chachapoyas', 'Cheto'),
('Amazonas', 'Chachapoyas', 'Chiliquin'),
('Amazonas', 'Chachapoyas', 'Chuquibamba'),
('Amazonas', 'Chachapoyas', 'Granada'),
('Amazonas', 'Chachapoyas', 'Huancas'),
('Amazonas', 'Chachapoyas', 'La Jalca'),
('Amazonas', 'Chachapoyas', 'Leimebamba'),
('Amazonas', 'Chachapoyas', 'Levanto'),
('Amazonas', 'Chachapoyas', 'Magdalena'),
('Amazonas', 'Chachapoyas', 'Mariscal Castilla'),
('Amazonas', 'Chachapoyas', 'Molinopampa'),
('Amazonas', 'Chachapoyas', 'Montevideo'),
('Amazonas', 'Chachapoyas', 'Olleros'),
('Amazonas', 'Chachapoyas', 'Quinjalca'),
('Amazonas', 'Chachapoyas', 'San Francisco de Daguas'),
('Amazonas', 'Chachapoyas', 'San Isidro de Maino'),
('Amazonas', 'Chachapoyas', 'Soloco'),
('Amazonas', 'Chachapoyas', 'Sonche'),
('Amazonas', 'Bagua', 'Bagua'),
('Amazonas', 'Bagua', 'Aramango'),
('Amazonas', 'Bagua', 'Copallin'),
('Amazonas', 'Bagua', 'El Parco'),
('Amazonas', 'Bagua', 'Imaza'),
('Amazonas', 'Bagua', 'La Peca'),
('Amazonas', 'Bongará', 'Jumbilla'),
('Amazonas', 'Bongará', 'Chisquilla'),
('Amazonas', 'Bongará', 'Churuja'),
('Amazonas', 'Bongará', 'Corosha'),
('Amazonas', 'Bongará', 'Cuispes'),
('Amazonas', 'Bongará', 'Florida'),
('Amazonas', 'Bongará', 'Jazan'),
('Amazonas', 'Bongará', 'Recta'),
('Amazonas', 'Bongará', 'San Carlos'),
('Amazonas', 'Bongará', 'Shipasbamba'),
('Amazonas', 'Bongará', 'Valera'),
('Amazonas', 'Bongará', 'Yambrasbamba'),
('Amazonas', 'Condorcanqui', 'Nieva'),
('Amazonas', 'Condorcanqui', 'El Cenepa'),
('Amazonas', 'Condorcanqui', 'Río Santiago'),
('Amazonas', 'Luya', 'Lamud'),
('Amazonas', 'Luya', 'Camporredondo'),
('Amazonas', 'Luya', 'Cocabamba'),
('Amazonas', 'Luya', 'Colcamar'),
('Amazonas', 'Luya', 'Conila'),
('Amazonas', 'Luya', 'Inguilpata'),
('Amazonas', 'Luya', 'Longuita'),
('Amazonas', 'Luya', 'Lonya Chico'),
('Amazonas', 'Luya', 'Luya'),
('Amazonas', 'Luya', 'Luya Viejo'),
('Amazonas', 'Luya', 'María'),
('Amazonas', 'Luya', 'Ocalli'),
('Amazonas', 'Luya', 'Ocumal'),
('Amazonas', 'Luya', 'Pisuquia'),
('Amazonas', 'Luya', 'Providencia'),
('Amazonas', 'Luya', 'San Cristóbal'),
('Amazonas', 'Luya', 'San Francisco de Yeso'),
('Amazonas', 'Luya', 'San Jerónimo'),
('Amazonas', 'Luya', 'San Juan de Lopecancha'),
('Amazonas', 'Luya', 'Santa Catalina'),
('Amazonas', 'Luya', 'Santo Tomas'),
('Amazonas', 'Luya', 'Tingo'),
('Amazonas', 'Luya', 'Trita'),
('Amazonas', 'Rodríguez de Mendoza', 'San Nicolás'),
('Amazonas', 'Rodríguez de Mendoza', 'Chirimoto'),
('Amazonas', 'Rodríguez de Mendoza', 'Cochamal'),
('Amazonas', 'Rodríguez de Mendoza', 'Huambo'),
('Amazonas', 'Rodríguez de Mendoza', 'Limabamba'),
('Amazonas', 'Rodríguez de Mendoza', 'Longar'),
('Amazonas', 'Rodríguez de Mendoza', 'Mariscal Benavides'),
('Amazonas', 'Rodríguez de Mendoza', 'Milpuc'),
('Amazonas', 'Rodríguez de Mendoza', 'Omia'),
('Amazonas', 'Rodríguez de Mendoza', 'Santa Rosa'),
('Amazonas', 'Rodríguez de Mendoza', 'Totora'),
('Amazonas', 'Rodríguez de Mendoza', 'Vista Alegre'),
('Amazonas', 'Utcubamba', 'Bagua Grande'),
('Amazonas', 'Utcubamba', 'Cajaruro'),
('Amazonas', 'Utcubamba', 'Cumba'),
('Amazonas', 'Utcubamba', 'El Milagro'),
('Amazonas', 'Utcubamba', 'Jamalca'),
('Amazonas', 'Utcubamba', 'Lonya Grande'),
('Amazonas', 'Utcubamba', 'Yamon'),
('Áncash', 'Huaraz', 'Huaraz'),
('Áncash', 'Huaraz', 'Cochabamba'),
('Áncash', 'Huaraz', 'Colcabamba'),
('Áncash', 'Huaraz', 'Huanchay'),
('Áncash', 'Huaraz', 'Independencia'),
('Áncash', 'Huaraz', 'Jangas'),
('Áncash', 'Huaraz', 'La Libertad'),
('Áncash', 'Huaraz', 'Olleros'),
('Áncash', 'Huaraz', 'Pampas Grande'),
('Áncash', 'Huaraz', 'Pariacoto'),
('Áncash', 'Huaraz', 'Pira'),
('Áncash', 'Huaraz', 'Tarica'),
('Áncash', 'Aija', 'Aija'),
('Áncash', 'Aija', 'Coris'),
('Áncash', 'Aija', 'Huacllan'),
('Áncash', 'Aija', 'La Merced'),
('Áncash', 'Aija', 'Succha'),
('Áncash', 'Antonio Raymondi', 'Llamellin'),
('Áncash', 'Antonio Raymondi', 'Aczo'),
('Áncash', 'Antonio Raymondi', 'Chaccho'),
('Áncash', 'Antonio Raymondi', 'Chingas'),
('Áncash', 'Antonio Raymondi', 'Mirgas'),
('Áncash', 'Antonio Raymondi', 'San Juan de Rontoy'),
('Áncash', 'Asunción', 'Chacas'),
('Áncash', 'Asunción', 'Acochaca'),
('Áncash', 'Bolognesi', 'Chiquian'),
('Áncash', 'Bolognesi', 'Abelardo Pardo Lezameta'),
('Áncash', 'Bolognesi', 'Antonio Raymondi'),
('Áncash', 'Bolognesi', 'Aquia'),
('Áncash', 'Bolognesi', 'Cajacay'),
('Áncash', 'Bolognesi', 'Canis'),
('Áncash', 'Bolognesi', 'Colquioc'),
('Áncash', 'Bolognesi', 'Huallanca'),
('Áncash', 'Bolognesi', 'Huasta'),
('Áncash', 'Bolognesi', 'Huayllacayan'),
('Áncash', 'Bolognesi', 'La Primavera'),
('Áncash', 'Bolognesi', 'Mangas'),
('Áncash', 'Bolognesi', 'Pacllon'),
('Áncash', 'Bolognesi', 'San Miguel de Corpanqui'),
('Áncash', 'Bolognesi', 'Ticllos'),
('Áncash', 'Carhuaz', 'Carhuaz'),
('Áncash', 'Carhuaz', 'Acopampa'),
('Áncash', 'Carhuaz', 'Amashca'),
('Áncash', 'Carhuaz', 'Anta'),
('Áncash', 'Carhuaz', 'Ataquero'),
('Áncash', 'Carhuaz', 'Marcara'),
('Áncash', 'Carhuaz', 'Pariahuanca'),
('Áncash', 'Carhuaz', 'San Miguel de Aco'),
('Áncash', 'Carhuaz', 'Shilla'),
('Áncash', 'Carhuaz', 'Tinco'),
('Áncash', 'Carhuaz', 'Yungar'),
('Áncash', 'Carlos Fermín Fitzcarrald', 'San Luis'),
('Áncash', 'Carlos Fermín Fitzcarrald', 'San Nicolás'),
('Áncash', 'Carlos Fermín Fitzcarrald', 'Yauya'),
('Áncash', 'Casma', 'Casma'),
('Áncash', 'Casma', 'Buena Vista Alta'),
('Áncash', 'Casma', 'Comandante Noel'),
('Áncash', 'Casma', 'Yautan'),
('Áncash', 'Corongo', 'Corongo'),
('Áncash', 'Corongo', 'Aco'),
('Áncash', 'Corongo', 'Bambas'),
('Áncash', 'Corongo', 'Cusca'),
('Áncash', 'Corongo', 'La Pampa'),
('Áncash', 'Corongo', 'Yanac'),
('Áncash', 'Corongo', 'Yupan'),
('Áncash', 'Huari', 'Huari'),
('Áncash', 'Huari', 'Anra'),
('Áncash', 'Huari', 'Cajay'),
('Áncash', 'Huari', 'Chavin de Huantar'),
('Áncash', 'Huari', 'Huacachi'),
('Áncash', 'Huari', 'Huacchis'),
('Áncash', 'Huari', 'Huachis'),
('Áncash', 'Huari', 'Huantar'),
('Áncash', 'Huari', 'Masin'),
('Áncash', 'Huari', 'Paucas'),
('Áncash', 'Huari', 'Ponto'),
('Áncash', 'Huari', 'Rahuapampa'),
('Áncash', 'Huari', 'Rapayan'),
('Áncash', 'Huari', 'San Marcos'),
('Áncash', 'Huari', 'San Pedro de Chana'),
('Áncash', 'Huari', 'Uco'),
('Áncash', 'Huarmey', 'Huarmey'),
('Áncash', 'Huarmey', 'Cochapeti'),
('Áncash', 'Huarmey', 'Culebras'),
('Áncash', 'Huarmey', 'Huayan'),
('Áncash', 'Huarmey', 'Malvas'),
('Áncash', 'Huaylas', 'Caraz'),
('Áncash', 'Huaylas', 'Huallanca'),
('Áncash', 'Huaylas', 'Huata'),
('Áncash', 'Huaylas', 'Huaylas'),
('Áncash', 'Huaylas', 'Mato'),
('Áncash', 'Huaylas', 'Pamparomas'),
('Áncash', 'Huaylas', 'Pueblo Libre'),
('Áncash', 'Huaylas', 'Santa Cruz'),
('Áncash', 'Huaylas', 'Santo Toribio'),
('Áncash', 'Huaylas', 'Yuracmarca'),
('Áncash', 'Mariscal Luzuriaga', 'Piscobamba'),
('Áncash', 'Mariscal Luzuriaga', 'Casca'),
('Áncash', 'Mariscal Luzuriaga', 'Eleazar Guzmán Barron'),
('Áncash', 'Mariscal Luzuriaga', 'Fidel Olivas Escudero'),
('Áncash', 'Mariscal Luzuriaga', 'Llama'),
('Áncash', 'Mariscal Luzuriaga', 'Llumpa'),
('Áncash', 'Mariscal Luzuriaga', 'Lucma'),
('Áncash', 'Mariscal Luzuriaga', 'Musga'),
('Áncash', 'Ocros', 'Ocros'),
('Áncash', 'Ocros', 'Acas'),
('Áncash', 'Ocros', 'Cajamarquilla'),
('Áncash', 'Ocros', 'Carhuapampa'),
('Áncash', 'Ocros', 'Cochas'),
('Áncash', 'Ocros', 'Congas'),
('Áncash', 'Ocros', 'Llipa'),
('Áncash', 'Ocros', 'San Cristóbal de Rajan'),
('Áncash', 'Ocros', 'San Pedro'),
('Áncash', 'Ocros', 'Santiago de Chilcas'),
('Áncash', 'Pallasca', 'Cabana'),
('Áncash', 'Pallasca', 'Bolognesi'),
('Áncash', 'Pallasca', 'Conchucos'),
('Áncash', 'Pallasca', 'Huacaschuque'),
('Áncash', 'Pallasca', 'Huandoval'),
('Áncash', 'Pallasca', 'Lacabamba'),
('Áncash', 'Pallasca', 'Llapo'),
('Áncash', 'Pallasca', 'Pallasca'),
('Áncash', 'Pallasca', 'Pampas'),
('Áncash', 'Pallasca', 'Santa Rosa'),
('Áncash', 'Pallasca', 'Tauca'),
('Áncash', 'Pomabamba', 'Pomabamba'),
('Áncash', 'Pomabamba', 'Huayllan'),
('Áncash', 'Pomabamba', 'Parobamba'),
('Áncash', 'Pomabamba', 'Quinuabamba'),
('Áncash', 'Recuay', 'Recuay'),
('Áncash', 'Recuay', 'Catac'),
('Áncash', 'Recuay', 'Cotaparaco'),
('Áncash', 'Recuay', 'Huayllapampa'),
('Áncash', 'Recuay', 'Llacllin'),
('Áncash', 'Recuay', 'Marca'),
('Áncash', 'Recuay', 'Pampas Chico'),
('Áncash', 'Recuay', 'Pararin'),
('Áncash', 'Recuay', 'Tapacocha'),
('Áncash', 'Recuay', 'Ticapampa'),
('Áncash', 'Santa', 'Chimbote'),
('Áncash', 'Santa', 'Cáceres del Perú'),
('Áncash', 'Santa', 'Coishco'),
('Áncash', 'Santa', 'Macate'),
('Áncash', 'Santa', 'Moro'),
('Áncash', 'Santa', 'Nepeña'),
('Áncash', 'Santa', 'Samanco'),
('Áncash', 'Santa', 'Santa'),
('Áncash', 'Santa', 'Nuevo Chimbote'),
('Áncash', 'Sihuas', 'Sihuas'),
('Áncash', 'Sihuas', 'Acobamba'),
('Áncash', 'Sihuas', 'Alfonso Ugarte'),
('Áncash', 'Sihuas', 'Cashapampa'),
('Áncash', 'Sihuas', 'Chingalpo'),
('Áncash', 'Sihuas', 'Huayllabamba'),
('Áncash', 'Sihuas', 'Quiches'),
('Áncash', 'Sihuas', 'Ragash'),
('Áncash', 'Sihuas', 'San Juan'),
('Áncash', 'Sihuas', 'Sicsibamba'),
('Áncash', 'Yungay', 'Yungay'),
('Áncash', 'Yungay', 'Cascapara'),
('Áncash', 'Yungay', 'Mancos'),
('Áncash', 'Yungay', 'Matacoto'),
('Áncash', 'Yungay', 'Quillo'),
('Áncash', 'Yungay', 'Ranrahirca'),
('Áncash', 'Yungay', 'Shupluy'),
('Áncash', 'Yungay', 'Yanama'),
('Apurímac', 'Abancay', 'Abancay'),
('Apurímac', 'Abancay', 'Chacoche'),
('Apurímac', 'Abancay', 'Circa'),
('Apurímac', 'Abancay', 'Curahuasi'),
('Apurímac', 'Abancay', 'Huanipaca'),
('Apurímac', 'Abancay', 'Lambrama'),
('Apurímac', 'Abancay', 'Pichirhua'),
('Apurímac', 'Abancay', 'San Pedro de Cachora'),
('Apurímac', 'Abancay', 'Tamburco'),
('Apurímac', 'Andahuaylas', 'Andahuaylas'),
('Apurímac', 'Andahuaylas', 'Andarapa'),
('Apurímac', 'Andahuaylas', 'Chiara'),
('Apurímac', 'Andahuaylas', 'Huancarama'),
('Apurímac', 'Andahuaylas', 'Huancaray'),
('Apurímac', 'Andahuaylas', 'Huayana'),
('Apurímac', 'Andahuaylas', 'Kishuara'),
('Apurímac', 'Andahuaylas', 'Pacobamba'),
('Apurímac', 'Andahuaylas', 'Pacucha'),
('Apurímac', 'Andahuaylas', 'Pampachiri'),
('Apurímac', 'Andahuaylas', 'Pomacocha'),
('Apurímac', 'Andahuaylas', 'San Antonio de Cachi'),
('Apurímac', 'Andahuaylas', 'San Jerónimo'),
('Apurímac', 'Andahuaylas', 'San Miguel de Chaccrampa'),
('Apurímac', 'Andahuaylas', 'Santa María de Chicmo'),
('Apurímac', 'Andahuaylas', 'Talavera'),
('Apurímac', 'Andahuaylas', 'Tumay Huaraca'),
('Apurímac', 'Andahuaylas', 'Turpo'),
('Apurímac', 'Andahuaylas', 'Kaquiabamba'),
('Apurímac', 'Andahuaylas', 'José María Arguedas'),
('Apurímac', 'Antabamba', 'Antabamba'),
('Apurímac', 'Antabamba', 'El Oro'),
('Apurímac', 'Antabamba', 'Huaquirca'),
('Apurímac', 'Antabamba', 'Juan Espinoza Medrano'),
('Apurímac', 'Antabamba', 'Oropesa'),
('Apurímac', 'Antabamba', 'Pachaconas'),
('Apurímac', 'Antabamba', 'Sabaino'),
('Apurímac', 'Aymaraes', 'Chalhuanca'),
('Apurímac', 'Aymaraes', 'Capaya'),
('Apurímac', 'Aymaraes', 'Caraybamba'),
('Apurímac', 'Aymaraes', 'Chapimarca'),
('Apurímac', 'Aymaraes', 'Colcabamba'),
('Apurímac', 'Aymaraes', 'Cotaruse'),
('Apurímac', 'Aymaraes', 'Huayllo'),
('Apurímac', 'Aymaraes', 'Justo Apu Sahuaraura'),
('Apurímac', 'Aymaraes', 'Lucre'),
('Apurímac', 'Aymaraes', 'Pocohuanca'),
('Apurímac', 'Aymaraes', 'San Juan de Chacña'),
('Apurímac', 'Aymaraes', 'Sañayca'),
('Apurímac', 'Aymaraes', 'Soraya'),
('Apurímac', 'Aymaraes', 'Tapairihua'),
('Apurímac', 'Aymaraes', 'Tintay'),
('Apurímac', 'Aymaraes', 'Toraya'),
('Apurímac', 'Aymaraes', 'Yanaca'),
('Apurímac', 'Cotabambas', 'Tambobamba'),
('Apurímac', 'Cotabambas', 'Cotabambas'),
('Apurímac', 'Cotabambas', 'Coyllurqui'),
('Apurímac', 'Cotabambas', 'Haquira'),
('Apurímac', 'Cotabambas', 'Mara'),
('Apurímac', 'Cotabambas', 'Challhuahuacho'),
('Apurímac', 'Chincheros', 'Chincheros'),
('Apurímac', 'Chincheros', 'Anco_Huallo'),
('Apurímac', 'Chincheros', 'Cocharcas'),
('Apurímac', 'Chincheros', 'Huaccana'),
('Apurímac', 'Chincheros', 'Ocobamba'),
('Apurímac', 'Chincheros', 'Ongoy'),
('Apurímac', 'Chincheros', 'Uranmarca'),
('Apurímac', 'Chincheros', 'Ranracancha'),
('Apurímac', 'Grau', 'Chuquibambilla'),
('Apurímac', 'Grau', 'Curpahuasi'),
('Apurímac', 'Grau', 'Gamarra'),
('Apurímac', 'Grau', 'Huayllati'),
('Apurímac', 'Grau', 'Mamara'),
('Apurímac', 'Grau', 'Micaela Bastidas'),
('Apurímac', 'Grau', 'Pataypampa'),
('Apurímac', 'Grau', 'Progreso'),
('Apurímac', 'Grau', 'San Antonio'),
('Apurímac', 'Grau', 'Santa Rosa'),
('Apurímac', 'Grau', 'Turpay'),
('Apurímac', 'Grau', 'Vilcabamba'),
('Apurímac', 'Grau', 'Virundo'),
('Apurímac', 'Grau', 'Curasco'),
('Arequipa', 'Arequipa', 'Arequipa'),
('Arequipa', 'Arequipa', 'Alto Selva Alegre'),
('Arequipa', 'Arequipa', 'Cayma'),
('Arequipa', 'Arequipa', 'Cerro Colorado'),
('Arequipa', 'Arequipa', 'Characato'),
('Arequipa', 'Arequipa', 'Chiguata'),
('Arequipa', 'Arequipa', 'Jacobo Hunter'),
('Arequipa', 'Arequipa', 'La Joya'),
('Arequipa', 'Arequipa', 'Mariano Melgar'),
('Arequipa', 'Arequipa', 'Miraflores'),
('Arequipa', 'Arequipa', 'Mollebaya'),
('Arequipa', 'Arequipa', 'Paucarpata'),
('Arequipa', 'Arequipa', 'Pocsi'),
('Arequipa', 'Arequipa', 'Polobaya'),
('Arequipa', 'Arequipa', 'Quequeña'),
('Arequipa', 'Arequipa', 'Sabandia'),
('Arequipa', 'Arequipa', 'Sachaca'),
('Arequipa', 'Arequipa', 'San Juan de Siguas'),
('Arequipa', 'Arequipa', 'San Juan de Tarucani'),
('Arequipa', 'Arequipa', 'Santa Isabel de Siguas'),
('Arequipa', 'Arequipa', 'Santa Rita de Siguas'),
('Arequipa', 'Arequipa', 'Socabaya'),
('Arequipa', 'Arequipa', 'Tiabaya'),
('Arequipa', 'Arequipa', 'Uchumayo'),
('Arequipa', 'Arequipa', 'Vitor'),
('Arequipa', 'Arequipa', 'Yanahuara'),
('Arequipa', 'Arequipa', 'Yarabamba'),
('Arequipa', 'Arequipa', 'Yura'),
('Arequipa', 'Arequipa', 'José Luis Bustamante Y Rivero'),
('Arequipa', 'Camaná', 'Camaná'),
('Arequipa', 'Camaná', 'José María Quimper'),
('Arequipa', 'Camaná', 'Mariano Nicolás Valcárcel'),
('Arequipa', 'Camaná', 'Mariscal Cáceres'),
('Arequipa', 'Camaná', 'Nicolás de Pierola'),
('Arequipa', 'Camaná', 'Ocoña'),
('Arequipa', 'Camaná', 'Quilca'),
('Arequipa', 'Camaná', 'Samuel Pastor'),
('Arequipa', 'Caravelí', 'Caravelí'),
('Arequipa', 'Caravelí', 'Acarí'),
('Arequipa', 'Caravelí', 'Atico'),
('Arequipa', 'Caravelí', 'Atiquipa'),
('Arequipa', 'Caravelí', 'Bella Unión'),
('Arequipa', 'Caravelí', 'Cahuacho'),
('Arequipa', 'Caravelí', 'Chala'),
('Arequipa', 'Caravelí', 'Chaparra'),
('Arequipa', 'Caravelí', 'Huanuhuanu'),
('Arequipa', 'Caravelí', 'Jaqui'),
('Arequipa', 'Caravelí', 'Lomas'),
('Arequipa', 'Caravelí', 'Quicacha'),
('Arequipa', 'Caravelí', 'Yauca'),
('Arequipa', 'Castilla', 'Aplao'),
('Arequipa', 'Castilla', 'Andagua'),
('Arequipa', 'Castilla', 'Ayo'),
('Arequipa', 'Castilla', 'Chachas'),
('Arequipa', 'Castilla', 'Chilcaymarca'),
('Arequipa', 'Castilla', 'Choco'),
('Arequipa', 'Castilla', 'Huancarqui'),
('Arequipa', 'Castilla', 'Machaguay'),
('Arequipa', 'Castilla', 'Orcopampa'),
('Arequipa', 'Castilla', 'Pampacolca'),
('Arequipa', 'Castilla', 'Tipan'),
('Arequipa', 'Castilla', 'Uñon'),
('Arequipa', 'Castilla', 'Uraca'),
('Arequipa', 'Castilla', 'Viraco'),
('Arequipa', 'Caylloma', 'Chivay'),
('Arequipa', 'Caylloma', 'Achoma'),
('Arequipa', 'Caylloma', 'Cabanaconde'),
('Arequipa', 'Caylloma', 'Callalli'),
('Arequipa', 'Caylloma', 'Caylloma'),
('Arequipa', 'Caylloma', 'Coporaque'),
('Arequipa', 'Caylloma', 'Huambo'),
('Arequipa', 'Caylloma', 'Huanca'),
('Arequipa', 'Caylloma', 'Ichupampa'),
('Arequipa', 'Caylloma', 'Lari'),
('Arequipa', 'Caylloma', 'Lluta'),
('Arequipa', 'Caylloma', 'Maca'),
('Arequipa', 'Caylloma', 'Madrigal'),
('Arequipa', 'Caylloma', 'San Antonio de Chuca'),
('Arequipa', 'Caylloma', 'Sibayo'),
('Arequipa', 'Caylloma', 'Tapay'),
('Arequipa', 'Caylloma', 'Tisco'),
('Arequipa', 'Caylloma', 'Tuti'),
('Arequipa', 'Caylloma', 'Yanque'),
('Arequipa', 'Caylloma', 'Majes'),
('Arequipa', 'Condesuyos', 'Chuquibamba'),
('Arequipa', 'Condesuyos', 'Andaray'),
('Arequipa', 'Condesuyos', 'Cayarani'),
('Arequipa', 'Condesuyos', 'Chichas'),
('Arequipa', 'Condesuyos', 'Iray'),
('Arequipa', 'Condesuyos', 'Río Grande'),
('Arequipa', 'Condesuyos', 'Salamanca'),
('Arequipa', 'Condesuyos', 'Yanaquihua'),
('Arequipa', 'Islay', 'Mollendo'),
('Arequipa', 'Islay', 'Cocachacra'),
('Arequipa', 'Islay', 'Dean Valdivia'),
('Arequipa', 'Islay', 'Islay'),
('Arequipa', 'Islay', 'Mejia'),
('Arequipa', 'Islay', 'Punta de Bombón'),
('Arequipa', 'La Uniòn', 'Cotahuasi'),
('Arequipa', 'La Uniòn', 'Alca'),
('Arequipa', 'La Uniòn', 'Charcana'),
('Arequipa', 'La Uniòn', 'Huaynacotas'),
('Arequipa', 'La Uniòn', 'Pampamarca'),
('Arequipa', 'La Uniòn', 'Puyca'),
('Arequipa', 'La Uniòn', 'Quechualla'),
('Arequipa', 'La Uniòn', 'Sayla'),
('Arequipa', 'La Uniòn', 'Tauria'),
('Arequipa', 'La Uniòn', 'Tomepampa'),
('Arequipa', 'La Uniòn', 'Toro'),
('Ayacucho', 'Huamanga', 'Ayacucho'),
('Ayacucho', 'Huamanga', 'Acocro'),
('Ayacucho', 'Huamanga', 'Acos Vinchos'),
('Ayacucho', 'Huamanga', 'Carmen Alto'),
('Ayacucho', 'Huamanga', 'Chiara'),
('Ayacucho', 'Huamanga', 'Ocros'),
('Ayacucho', 'Huamanga', 'Pacaycasa'),
('Ayacucho', 'Huamanga', 'Quinua'),
('Ayacucho', 'Huamanga', 'San José de Ticllas'),
('Ayacucho', 'Huamanga', 'San Juan Bautista'),
('Ayacucho', 'Huamanga', 'Santiago de Pischa'),
('Ayacucho', 'Huamanga', 'Socos'),
('Ayacucho', 'Huamanga', 'Tambillo'),
('Ayacucho', 'Huamanga', 'Vinchos'),
('Ayacucho', 'Huamanga', 'Jesús Nazareno'),
('Ayacucho', 'Huamanga', 'Andrés Avelino Cáceres Dorregaray'),
('Ayacucho', 'Cangallo', 'Cangallo'),
('Ayacucho', 'Cangallo', 'Chuschi'),
('Ayacucho', 'Cangallo', 'Los Morochucos'),
('Ayacucho', 'Cangallo', 'María Parado de Bellido'),
('Ayacucho', 'Cangallo', 'Paras'),
('Ayacucho', 'Cangallo', 'Totos'),
('Ayacucho', 'Huanca Sancos', 'Sancos'),
('Ayacucho', 'Huanca Sancos', 'Carapo'),
('Ayacucho', 'Huanca Sancos', 'Sacsamarca'),
('Ayacucho', 'Huanca Sancos', 'Santiago de Lucanamarca'),
('Ayacucho', 'Huanta', 'Huanta'),
('Ayacucho', 'Huanta', 'Ayahuanco'),
('Ayacucho', 'Huanta', 'Huamanguilla'),
('Ayacucho', 'Huanta', 'Iguain'),
('Ayacucho', 'Huanta', 'Luricocha'),
('Ayacucho', 'Huanta', 'Santillana'),
('Ayacucho', 'Huanta', 'Sivia'),
('Ayacucho', 'Huanta', 'Llochegua'),
('Ayacucho', 'Huanta', 'Canayre'),
('Ayacucho', 'Huanta', 'Uchuraccay'),
('Ayacucho', 'Huanta', 'Pucacolpa'),
('Ayacucho', 'La Mar', 'San Miguel'),
('Ayacucho', 'La Mar', 'Anco'),
('Ayacucho', 'La Mar', 'Ayna'),
('Ayacucho', 'La Mar', 'Chilcas'),
('Ayacucho', 'La Mar', 'Chungui'),
('Ayacucho', 'La Mar', 'Luis Carranza'),
('Ayacucho', 'La Mar', 'Santa Rosa'),
('Ayacucho', 'La Mar', 'Tambo'),
('Ayacucho', 'La Mar', 'Samugari'),
('Ayacucho', 'La Mar', 'Anchihuay'),
('Ayacucho', 'Lucanas', 'Puquio'),
('Ayacucho', 'Lucanas', 'Aucara'),
('Ayacucho', 'Lucanas', 'Cabana'),
('Ayacucho', 'Lucanas', 'Carmen Salcedo'),
('Ayacucho', 'Lucanas', 'Chaviña'),
('Ayacucho', 'Lucanas', 'Chipao'),
('Ayacucho', 'Lucanas', 'Huac-Huas'),
('Ayacucho', 'Lucanas', 'Laramate'),
('Ayacucho', 'Lucanas', 'Leoncio Prado'),
('Ayacucho', 'Lucanas', 'Llauta'),
('Ayacucho', 'Lucanas', 'Lucanas'),
('Ayacucho', 'Lucanas', 'Ocaña'),
('Ayacucho', 'Lucanas', 'Otoca'),
('Ayacucho', 'Lucanas', 'Saisa'),
('Ayacucho', 'Lucanas', 'San Cristóbal'),
('Ayacucho', 'Lucanas', 'San Juan'),
('Ayacucho', 'Lucanas', 'San Pedro'),
('Ayacucho', 'Lucanas', 'San Pedro de Palco'),
('Ayacucho', 'Lucanas', 'Sancos'),
('Ayacucho', 'Lucanas', 'Santa Ana de Huaycahuacho'),
('Ayacucho', 'Lucanas', 'Santa Lucia'),
('Ayacucho', 'Parinacochas', 'Coracora'),
('Ayacucho', 'Parinacochas', 'Chumpi'),
('Ayacucho', 'Parinacochas', 'Coronel Castañeda'),
('Ayacucho', 'Parinacochas', 'Pacapausa'),
('Ayacucho', 'Parinacochas', 'Pullo'),
('Ayacucho', 'Parinacochas', 'Puyusca'),
('Ayacucho', 'Parinacochas', 'San Francisco de Ravacayco'),
('Ayacucho', 'Parinacochas', 'Upahuacho'),
('Ayacucho', 'Pàucar del Sara Sara', 'Pausa'),
('Ayacucho', 'Pàucar del Sara Sara', 'Colta'),
('Ayacucho', 'Pàucar del Sara Sara', 'Corculla'),
('Ayacucho', 'Pàucar del Sara Sara', 'Lampa'),
('Ayacucho', 'Pàucar del Sara Sara', 'Marcabamba'),
('Ayacucho', 'Pàucar del Sara Sara', 'Oyolo'),
('Ayacucho', 'Pàucar del Sara Sara', 'Pararca'),
('Ayacucho', 'Pàucar del Sara Sara', 'San Javier de Alpabamba'),
('Ayacucho', 'Pàucar del Sara Sara', 'San José de Ushua'),
('Ayacucho', 'Pàucar del Sara Sara', 'Sara Sara'),
('Ayacucho', 'Sucre', 'Querobamba'),
('Ayacucho', 'Sucre', 'Belén'),
('Ayacucho', 'Sucre', 'Chalcos'),
('Ayacucho', 'Sucre', 'Chilcayoc'),
('Ayacucho', 'Sucre', 'Huacaña'),
('Ayacucho', 'Sucre', 'Morcolla'),
('Ayacucho', 'Sucre', 'Paico'),
('Ayacucho', 'Sucre', 'San Pedro de Larcay'),
('Ayacucho', 'Sucre', 'San Salvador de Quije'),
('Ayacucho', 'Sucre', 'Santiago de Paucaray'),
('Ayacucho', 'Sucre', 'Soras'),
('Ayacucho', 'Víctor Fajardo', 'Huancapi'),
('Ayacucho', 'Víctor Fajardo', 'Alcamenca'),
('Ayacucho', 'Víctor Fajardo', 'Apongo'),
('Ayacucho', 'Víctor Fajardo', 'Asquipata'),
('Ayacucho', 'Víctor Fajardo', 'Canaria'),
('Ayacucho', 'Víctor Fajardo', 'Cayara'),
('Ayacucho', 'Víctor Fajardo', 'Colca'),
('Ayacucho', 'Víctor Fajardo', 'Huamanquiquia'),
('Ayacucho', 'Víctor Fajardo', 'Huancaraylla'),
('Ayacucho', 'Víctor Fajardo', 'Huaya'),
('Ayacucho', 'Víctor Fajardo', 'Sarhua'),
('Ayacucho', 'Víctor Fajardo', 'Vilcanchos'),
('Ayacucho', 'Vilcas Huamán', 'Vilcas Huaman'),
('Ayacucho', 'Vilcas Huamán', 'Accomarca'),
('Ayacucho', 'Vilcas Huamán', 'Carhuanca'),
('Ayacucho', 'Vilcas Huamán', 'Concepción'),
('Ayacucho', 'Vilcas Huamán', 'Huambalpa'),
('Ayacucho', 'Vilcas Huamán', 'Independencia'),
('Ayacucho', 'Vilcas Huamán', 'Saurama'),
('Ayacucho', 'Vilcas Huamán', 'Vischongo'),
('Cajamarca', 'Cajamarca', 'Cajamarca'),
('Cajamarca', 'Cajamarca', 'Asunción'),
('Cajamarca', 'Cajamarca', 'Chetilla'),
('Cajamarca', 'Cajamarca', 'Cospan'),
('Cajamarca', 'Cajamarca', 'Encañada'),
('Cajamarca', 'Cajamarca', 'Jesús'),
('Cajamarca', 'Cajamarca', 'Llacanora'),
('Cajamarca', 'Cajamarca', 'Los Baños del Inca'),
('Cajamarca', 'Cajamarca', 'Magdalena'),
('Cajamarca', 'Cajamarca', 'Matara'),
('Cajamarca', 'Cajamarca', 'Namora'),
('Cajamarca', 'Cajamarca', 'San Juan'),
('Cajamarca', 'Cajabamba', 'Cajabamba'),
('Cajamarca', 'Cajabamba', 'Cachachi'),
('Cajamarca', 'Cajabamba', 'Condebamba'),
('Cajamarca', 'Cajabamba', 'Sitacocha'),
('Cajamarca', 'Celendín', 'Celendín'),
('Cajamarca', 'Celendín', 'Chumuch'),
('Cajamarca', 'Celendín', 'Cortegana'),
('Cajamarca', 'Celendín', 'Huasmin'),
('Cajamarca', 'Celendín', 'Jorge Chávez'),
('Cajamarca', 'Celendín', 'José Gálvez'),
('Cajamarca', 'Celendín', 'Miguel Iglesias'),
('Cajamarca', 'Celendín', 'Oxamarca'),
('Cajamarca', 'Celendín', 'Sorochuco'),
('Cajamarca', 'Celendín', 'Sucre'),
('Cajamarca', 'Celendín', 'Utco'),
('Cajamarca', 'Celendín', 'La Libertad de Pallan'),
('Cajamarca', 'Chota', 'Chota'),
('Cajamarca', 'Chota', 'Anguia'),
('Cajamarca', 'Chota', 'Chadin'),
('Cajamarca', 'Chota', 'Chiguirip'),
('Cajamarca', 'Chota', 'Chimban'),
('Cajamarca', 'Chota', 'Choropampa'),
('Cajamarca', 'Chota', 'Cochabamba'),
('Cajamarca', 'Chota', 'Conchan'),
('Cajamarca', 'Chota', 'Huambos'),
('Cajamarca', 'Chota', 'Lajas'),
('Cajamarca', 'Chota', 'Llama'),
('Cajamarca', 'Chota', 'Miracosta'),
('Cajamarca', 'Chota', 'Paccha'),
('Cajamarca', 'Chota', 'Pion'),
('Cajamarca', 'Chota', 'Querocoto'),
('Cajamarca', 'Chota', 'San Juan de Licupis'),
('Cajamarca', 'Chota', 'Tacabamba'),
('Cajamarca', 'Chota', 'Tocmoche'),
('Cajamarca', 'Chota', 'Chalamarca'),
('Cajamarca', 'Contumazá', 'Contumaza'),
('Cajamarca', 'Contumazá', 'Chilete'),
('Cajamarca', 'Contumazá', 'Cupisnique'),
('Cajamarca', 'Contumazá', 'Guzmango'),
('Cajamarca', 'Contumazá', 'San Benito'),
('Cajamarca', 'Contumazá', 'Santa Cruz de Toledo'),
('Cajamarca', 'Contumazá', 'Tantarica'),
('Cajamarca', 'Contumazá', 'Yonan'),
('Cajamarca', 'Cutervo', 'Cutervo'),
('Cajamarca', 'Cutervo', 'Callayuc'),
('Cajamarca', 'Cutervo', 'Choros'),
('Cajamarca', 'Cutervo', 'Cujillo'),
('Cajamarca', 'Cutervo', 'La Ramada'),
('Cajamarca', 'Cutervo', 'Pimpingos'),
('Cajamarca', 'Cutervo', 'Querocotillo'),
('Cajamarca', 'Cutervo', 'San Andrés de Cutervo'),
('Cajamarca', 'Cutervo', 'San Juan de Cutervo'),
('Cajamarca', 'Cutervo', 'San Luis de Lucma'),
('Cajamarca', 'Cutervo', 'Santa Cruz'),
('Cajamarca', 'Cutervo', 'Santo Domingo de la Capilla'),
('Cajamarca', 'Cutervo', 'Santo Tomas'),
('Cajamarca', 'Cutervo', 'Socota'),
('Cajamarca', 'Cutervo', 'Toribio Casanova'),
('Cajamarca', 'Hualgayoc', 'Bambamarca'),
('Cajamarca', 'Hualgayoc', 'Chugur'),
('Cajamarca', 'Hualgayoc', 'Hualgayoc'),
('Cajamarca', 'Jaén', 'Jaén'),
('Cajamarca', 'Jaén', 'Bellavista'),
('Cajamarca', 'Jaén', 'Chontali'),
('Cajamarca', 'Jaén', 'Colasay'),
('Cajamarca', 'Jaén', 'Huabal'),
('Cajamarca', 'Jaén', 'Las Pirias'),
('Cajamarca', 'Jaén', 'Pomahuaca'),
('Cajamarca', 'Jaén', 'Pucara'),
('Cajamarca', 'Jaén', 'Sallique'),
('Cajamarca', 'Jaén', 'San Felipe'),
('Cajamarca', 'Jaén', 'San José del Alto'),
('Cajamarca', 'Jaén', 'Santa Rosa'),
('Cajamarca', 'San Ignacio', 'San Ignacio'),
('Cajamarca', 'San Ignacio', 'Chirinos'),
('Cajamarca', 'San Ignacio', 'Huarango'),
('Cajamarca', 'San Ignacio', 'La Coipa'),
('Cajamarca', 'San Ignacio', 'Namballe'),
('Cajamarca', 'San Ignacio', 'San José de Lourdes'),
('Cajamarca', 'San Ignacio', 'Tabaconas'),
('Cajamarca', 'San Marcos', 'Pedro Gálvez'),
('Cajamarca', 'San Marcos', 'Chancay'),
('Cajamarca', 'San Marcos', 'Eduardo Villanueva'),
('Cajamarca', 'San Marcos', 'Gregorio Pita'),
('Cajamarca', 'San Marcos', 'Ichocan'),
('Cajamarca', 'San Marcos', 'José Manuel Quiroz'),
('Cajamarca', 'San Marcos', 'José Sabogal'),
('Cajamarca', 'San Miguel', 'San Miguel'),
('Cajamarca', 'San Miguel', 'Bolívar'),
('Cajamarca', 'San Miguel', 'Calquis'),
('Cajamarca', 'San Miguel', 'Catilluc'),
('Cajamarca', 'San Miguel', 'El Prado'),
('Cajamarca', 'San Miguel', 'La Florida'),
('Cajamarca', 'San Miguel', 'Llapa'),
('Cajamarca', 'San Miguel', 'Nanchoc'),
('Cajamarca', 'San Miguel', 'Niepos'),
('Cajamarca', 'San Miguel', 'San Gregorio'),
('Cajamarca', 'San Miguel', 'San Silvestre de Cochan'),
('Cajamarca', 'San Miguel', 'Tongod'),
('Cajamarca', 'San Miguel', 'Unión Agua Blanca'),
('Cajamarca', 'San Pablo', 'San Pablo'),
('Cajamarca', 'San Pablo', 'San Bernardino'),
('Cajamarca', 'San Pablo', 'San Luis'),
('Cajamarca', 'San Pablo', 'Tumbaden'),
('Cajamarca', 'Santa Cruz', 'Santa Cruz'),
('Cajamarca', 'Santa Cruz', 'Andabamba'),
('Cajamarca', 'Santa Cruz', 'Catache'),
('Cajamarca', 'Santa Cruz', 'Chancaybaños'),
('Cajamarca', 'Santa Cruz', 'La Esperanza'),
('Cajamarca', 'Santa Cruz', 'Ninabamba'),
('Cajamarca', 'Santa Cruz', 'Pulan'),
('Cajamarca', 'Santa Cruz', 'Saucepampa'),
('Cajamarca', 'Santa Cruz', 'Sexi'),
('Cajamarca', 'Santa Cruz', 'Uticyacu'),
('Cajamarca', 'Santa Cruz', 'Yauyucan'),
('Callao', 'Prov. Const. del Callao', 'Callao'),
('Callao', 'Prov. Const. del Callao', 'Bellavista'),
('Callao', 'Prov. Const. del Callao', 'Carmen de la Legua Reynoso'),
('Callao', 'Prov. Const. del Callao', 'La Perla'),
('Callao', 'Prov. Const. del Callao', 'La Punta'),
('Callao', 'Prov. Const. del Callao', 'Ventanilla'),
('Callao', 'Prov. Const. del Callao', 'Mi Perú'),
('Cusco', 'Cusco', 'Cusco'),
('Cusco', 'Cusco', 'Ccorca'),
('Cusco', 'Cusco', 'Poroy'),
('Cusco', 'Cusco', 'San Jerónimo'),
('Cusco', 'Cusco', 'San Sebastian'),
('Cusco', 'Cusco', 'Santiago'),
('Cusco', 'Cusco', 'Saylla'),
('Cusco', 'Cusco', 'Wanchaq'),
('Cusco', 'Acomayo', 'Acomayo'),
('Cusco', 'Acomayo', 'Acopia'),
('Cusco', 'Acomayo', 'Acos'),
('Cusco', 'Acomayo', 'Mosoc Llacta'),
('Cusco', 'Acomayo', 'Pomacanchi'),
('Cusco', 'Acomayo', 'Rondocan'),
('Cusco', 'Acomayo', 'Sangarara'),
('Cusco', 'Anta', 'Anta'),
('Cusco', 'Anta', 'Ancahuasi'),
('Cusco', 'Anta', 'Cachimayo'),
('Cusco', 'Anta', 'Chinchaypujio'),
('Cusco', 'Anta', 'Huarocondo'),
('Cusco', 'Anta', 'Limatambo'),
('Cusco', 'Anta', 'Mollepata'),
('Cusco', 'Anta', 'Pucyura'),
('Cusco', 'Anta', 'Zurite'),
('Cusco', 'Calca', 'Calca'),
('Cusco', 'Calca', 'Coya'),
('Cusco', 'Calca', 'Lamay'),
('Cusco', 'Calca', 'Lares'),
('Cusco', 'Calca', 'Pisac'),
('Cusco', 'Calca', 'San Salvador'),
('Cusco', 'Calca', 'Taray'),
('Cusco', 'Calca', 'Yanatile'),
('Cusco', 'Canas', 'Yanaoca'),
('Cusco', 'Canas', 'Checca'),
('Cusco', 'Canas', 'Kunturkanki'),
('Cusco', 'Canas', 'Langui'),
('Cusco', 'Canas', 'Layo'),
('Cusco', 'Canas', 'Pampamarca'),
('Cusco', 'Canas', 'Quehue'),
('Cusco', 'Canas', 'Tupac Amaru'),
('Cusco', 'Canchis', 'Sicuani'),
('Cusco', 'Canchis', 'Checacupe'),
('Cusco', 'Canchis', 'Combapata'),
('Cusco', 'Canchis', 'Marangani'),
('Cusco', 'Canchis', 'Pitumarca'),
('Cusco', 'Canchis', 'San Pablo'),
('Cusco', 'Canchis', 'San Pedro'),
('Cusco', 'Canchis', 'Tinta'),
('Cusco', 'Chumbivilcas', 'Santo Tomas'),
('Cusco', 'Chumbivilcas', 'Capacmarca'),
('Cusco', 'Chumbivilcas', 'Chamaca'),
('Cusco', 'Chumbivilcas', 'Colquemarca'),
('Cusco', 'Chumbivilcas', 'Livitaca'),
('Cusco', 'Chumbivilcas', 'Llusco'),
('Cusco', 'Chumbivilcas', 'Quiñota'),
('Cusco', 'Chumbivilcas', 'Velille'),
('Cusco', 'Espinar', 'Espinar'),
('Cusco', 'Espinar', 'Condoroma'),
('Cusco', 'Espinar', 'Coporaque'),
('Cusco', 'Espinar', 'Ocoruro'),
('Cusco', 'Espinar', 'Pallpata'),
('Cusco', 'Espinar', 'Pichigua'),
('Cusco', 'Espinar', 'Suyckutambo'),
('Cusco', 'Espinar', 'Alto Pichigua'),
('Cusco', 'La Convención', 'Santa Ana'),
('Cusco', 'La Convención', 'Echarate'),
('Cusco', 'La Convención', 'Huayopata'),
('Cusco', 'La Convención', 'Maranura'),
('Cusco', 'La Convención', 'Ocobamba'),
('Cusco', 'La Convención', 'Quellouno'),
('Cusco', 'La Convención', 'Kimbiri'),
('Cusco', 'La Convención', 'Santa Teresa'),
('Cusco', 'La Convención', 'Vilcabamba'),
('Cusco', 'La Convención', 'Pichari'),
('Cusco', 'La Convención', 'Inkawasi'),
('Cusco', 'La Convención', 'Villa Virgen'),
('Cusco', 'La Convención', 'Villa Kintiarina'),
('Cusco', 'Paruro', 'Paruro'),
('Cusco', 'Paruro', 'Accha'),
('Cusco', 'Paruro', 'Ccapi'),
('Cusco', 'Paruro', 'Colcha'),
('Cusco', 'Paruro', 'Huanoquite'),
('Cusco', 'Paruro', 'Omacha'),
('Cusco', 'Paruro', 'Paccaritambo'),
('Cusco', 'Paruro', 'Pillpinto'),
('Cusco', 'Paruro', 'Yaurisque'),
('Cusco', 'Paucartambo', 'Paucartambo'),
('Cusco', 'Paucartambo', 'Caicay'),
('Cusco', 'Paucartambo', 'Challabamba'),
('Cusco', 'Paucartambo', 'Colquepata'),
('Cusco', 'Paucartambo', 'Huancarani'),
('Cusco', 'Paucartambo', 'Kosñipata'),
('Cusco', 'Quispicanchi', 'Urcos'),
('Cusco', 'Quispicanchi', 'Andahuaylillas'),
('Cusco', 'Quispicanchi', 'Camanti'),
('Cusco', 'Quispicanchi', 'Ccarhuayo'),
('Cusco', 'Quispicanchi', 'Ccatca'),
('Cusco', 'Quispicanchi', 'Cusipata'),
('Cusco', 'Quispicanchi', 'Huaro'),
('Cusco', 'Quispicanchi', 'Lucre'),
('Cusco', 'Quispicanchi', 'Marcapata'),
('Cusco', 'Quispicanchi', 'Ocongate'),
('Cusco', 'Quispicanchi', 'Oropesa'),
('Cusco', 'Quispicanchi', 'Quiquijana'),
('Cusco', 'Urubamba', 'Urubamba'),
('Cusco', 'Urubamba', 'Chinchero'),
('Cusco', 'Urubamba', 'Huayllabamba'),
('Cusco', 'Urubamba', 'Machupicchu'),
('Cusco', 'Urubamba', 'Maras'),
('Cusco', 'Urubamba', 'Ollantaytambo'),
('Cusco', 'Urubamba', 'Yucay'),
('Huancavelica', 'Huancavelica', 'Huancavelica'),
('Huancavelica', 'Huancavelica', 'Acobambilla'),
('Huancavelica', 'Huancavelica', 'Acoria'),
('Huancavelica', 'Huancavelica', 'Conayca'),
('Huancavelica', 'Huancavelica', 'Cuenca'),
('Huancavelica', 'Huancavelica', 'Huachocolpa'),
('Huancavelica', 'Huancavelica', 'Huayllahuara'),
('Huancavelica', 'Huancavelica', 'Izcuchaca'),
('Huancavelica', 'Huancavelica', 'Laria'),
('Huancavelica', 'Huancavelica', 'Manta'),
('Huancavelica', 'Huancavelica', 'Mariscal Cáceres'),
('Huancavelica', 'Huancavelica', 'Moya'),
('Huancavelica', 'Huancavelica', 'Nuevo Occoro'),
('Huancavelica', 'Huancavelica', 'Palca'),
('Huancavelica', 'Huancavelica', 'Pilchaca'),
('Huancavelica', 'Huancavelica', 'Vilca'),
('Huancavelica', 'Huancavelica', 'Yauli'),
('Huancavelica', 'Huancavelica', 'Ascensión'),
('Huancavelica', 'Huancavelica', 'Huando'),
('Huancavelica', 'Acobamba', 'Acobamba'),
('Huancavelica', 'Acobamba', 'Andabamba'),
('Huancavelica', 'Acobamba', 'Anta'),
('Huancavelica', 'Acobamba', 'Caja'),
('Huancavelica', 'Acobamba', 'Marcas'),
('Huancavelica', 'Acobamba', 'Paucara'),
('Huancavelica', 'Acobamba', 'Pomacocha'),
('Huancavelica', 'Acobamba', 'Rosario'),
('Huancavelica', 'Angaraes', 'Lircay'),
('Huancavelica', 'Angaraes', 'Anchonga'),
('Huancavelica', 'Angaraes', 'Callanmarca'),
('Huancavelica', 'Angaraes', 'Ccochaccasa'),
('Huancavelica', 'Angaraes', 'Chincho'),
('Huancavelica', 'Angaraes', 'Congalla'),
('Huancavelica', 'Angaraes', 'Huanca-Huanca'),
('Huancavelica', 'Angaraes', 'Huayllay Grande'),
('Huancavelica', 'Angaraes', 'Julcamarca'),
('Huancavelica', 'Angaraes', 'San Antonio de Antaparco'),
('Huancavelica', 'Angaraes', 'Santo Tomas de Pata'),
('Huancavelica', 'Angaraes', 'Secclla'),
('Huancavelica', 'Castrovirreyna', 'Castrovirreyna'),
('Huancavelica', 'Castrovirreyna', 'Arma'),
('Huancavelica', 'Castrovirreyna', 'Aurahua'),
('Huancavelica', 'Castrovirreyna', 'Capillas'),
('Huancavelica', 'Castrovirreyna', 'Chupamarca'),
('Huancavelica', 'Castrovirreyna', 'Cocas'),
('Huancavelica', 'Castrovirreyna', 'Huachos'),
('Huancavelica', 'Castrovirreyna', 'Huamatambo'),
('Huancavelica', 'Castrovirreyna', 'Mollepampa'),
('Huancavelica', 'Castrovirreyna', 'San Juan'),
('Huancavelica', 'Castrovirreyna', 'Santa Ana'),
('Huancavelica', 'Castrovirreyna', 'Tantara'),
('Huancavelica', 'Castrovirreyna', 'Ticrapo'),
('Huancavelica', 'Churcampa', 'Churcampa'),
('Huancavelica', 'Churcampa', 'Anco'),
('Huancavelica', 'Churcampa', 'Chinchihuasi'),
('Huancavelica', 'Churcampa', 'El Carmen'),
('Huancavelica', 'Churcampa', 'La Merced'),
('Huancavelica', 'Churcampa', 'Locroja'),
('Huancavelica', 'Churcampa', 'Paucarbamba'),
('Huancavelica', 'Churcampa', 'San Miguel de Mayocc'),
('Huancavelica', 'Churcampa', 'San Pedro de Coris'),
('Huancavelica', 'Churcampa', 'Pachamarca'),
('Huancavelica', 'Churcampa', 'Cosme'),
('Huancavelica', 'Huaytará', 'Huaytara'),
('Huancavelica', 'Huaytará', 'Ayavi'),
('Huancavelica', 'Huaytará', 'Córdova'),
('Huancavelica', 'Huaytará', 'Huayacundo Arma'),
('Huancavelica', 'Huaytará', 'Laramarca'),
('Huancavelica', 'Huaytará', 'Ocoyo'),
('Huancavelica', 'Huaytará', 'Pilpichaca'),
('Huancavelica', 'Huaytará', 'Querco'),
('Huancavelica', 'Huaytará', 'Quito-Arma'),
('Huancavelica', 'Huaytará', 'San Antonio de Cusicancha'),
('Huancavelica', 'Huaytará', 'San Francisco de Sangayaico'),
('Huancavelica', 'Huaytará', 'San Isidro'),
('Huancavelica', 'Huaytará', 'Santiago de Chocorvos'),
('Huancavelica', 'Huaytará', 'Santiago de Quirahuara'),
('Huancavelica', 'Huaytará', 'Santo Domingo de Capillas'),
('Huancavelica', 'Huaytará', 'Tambo'),
('Huancavelica', 'Tayacaja', 'Pampas'),
('Huancavelica', 'Tayacaja', 'Acostambo'),
('Huancavelica', 'Tayacaja', 'Acraquia'),
('Huancavelica', 'Tayacaja', 'Ahuaycha'),
('Huancavelica', 'Tayacaja', 'Colcabamba'),
('Huancavelica', 'Tayacaja', 'Daniel Hernández'),
('Huancavelica', 'Tayacaja', 'Huachocolpa'),
('Huancavelica', 'Tayacaja', 'Huaribamba'),
('Huancavelica', 'Tayacaja', 'Ñahuimpuquio'),
('Huancavelica', 'Tayacaja', 'Pazos'),
('Huancavelica', 'Tayacaja', 'Quishuar'),
('Huancavelica', 'Tayacaja', 'Salcabamba'),
('Huancavelica', 'Tayacaja', 'Salcahuasi'),
('Huancavelica', 'Tayacaja', 'San Marcos de Rocchac'),
('Huancavelica', 'Tayacaja', 'Surcubamba'),
('Huancavelica', 'Tayacaja', 'Tintay Puncu'),
('Huancavelica', 'Tayacaja', 'Quichuas'),
('Huancavelica', 'Tayacaja', 'Andaymarca'),
('Huánuco', 'Huánuco', 'Huanuco'),
('Huánuco', 'Huánuco', 'Amarilis'),
('Huánuco', 'Huánuco', 'Chinchao'),
('Huánuco', 'Huánuco', 'Churubamba'),
('Huánuco', 'Huánuco', 'Margos'),
('Huánuco', 'Huánuco', 'Quisqui (Kichki)'),
('Huánuco', 'Huánuco', 'San Francisco de Cayran'),
('Huánuco', 'Huánuco', 'San Pedro de Chaulan'),
('Huánuco', 'Huánuco', 'Santa María del Valle'),
('Huánuco', 'Huánuco', 'Yarumayo'),
('Huánuco', 'Huánuco', 'Pillco Marca'),
('Huánuco', 'Huánuco', 'Yacus'),
('Huánuco', 'Ambo', 'Ambo'),
('Huánuco', 'Ambo', 'Cayna'),
('Huánuco', 'Ambo', 'Colpas'),
('Huánuco', 'Ambo', 'Conchamarca'),
('Huánuco', 'Ambo', 'Huacar'),
('Huánuco', 'Ambo', 'San Francisco'),
('Huánuco', 'Ambo', 'San Rafael'),
('Huánuco', 'Ambo', 'Tomay Kichwa'),
('Huánuco', 'Dos de Mayo', 'La Unión'),
('Huánuco', 'Dos de Mayo', 'Chuquis'),
('Huánuco', 'Dos de Mayo', 'Marías'),
('Huánuco', 'Dos de Mayo', 'Pachas'),
('Huánuco', 'Dos de Mayo', 'Quivilla'),
('Huánuco', 'Dos de Mayo', 'Ripan'),
('Huánuco', 'Dos de Mayo', 'Shunqui'),
('Huánuco', 'Dos de Mayo', 'Sillapata'),
('Huánuco', 'Dos de Mayo', 'Yanas'),
('Huánuco', 'Huacaybamba', 'Huacaybamba'),
('Huánuco', 'Huacaybamba', 'Canchabamba'),
('Huánuco', 'Huacaybamba', 'Cochabamba'),
('Huánuco', 'Huacaybamba', 'Pinra'),
('Huánuco', 'Huamalíes', 'Llata'),
('Huánuco', 'Huamalíes', 'Arancay'),
('Huánuco', 'Huamalíes', 'Chavín de Pariarca'),
('Huánuco', 'Huamalíes', 'Jacas Grande'),
('Huánuco', 'Huamalíes', 'Jircan'),
('Huánuco', 'Huamalíes', 'Miraflores'),
('Huánuco', 'Huamalíes', 'Monzón'),
('Huánuco', 'Huamalíes', 'Punchao'),
('Huánuco', 'Huamalíes', 'Puños'),
('Huánuco', 'Huamalíes', 'Singa'),
('Huánuco', 'Huamalíes', 'Tantamayo'),
('Huánuco', 'Leoncio Prado', 'Rupa-Rupa'),
('Huánuco', 'Leoncio Prado', 'Daniel Alomía Robles'),
('Huánuco', 'Leoncio Prado', 'Hermílio Valdizan'),
('Huánuco', 'Leoncio Prado', 'José Crespo y Castillo'),
('Huánuco', 'Leoncio Prado', 'Luyando'),
('Huánuco', 'Leoncio Prado', 'Mariano Damaso Beraun'),
('Huánuco', 'Marañón', 'Huacrachuco'),
('Huánuco', 'Marañón', 'Cholon'),
('Huánuco', 'Marañón', 'San Buenaventura'),
('Huánuco', 'Pachitea', 'Panao'),
('Huánuco', 'Pachitea', 'Chaglla'),
('Huánuco', 'Pachitea', 'Molino'),
('Huánuco', 'Pachitea', 'Umari'),
('Huánuco', 'Puerto Inca', 'Puerto Inca'),
('Huánuco', 'Puerto Inca', 'Codo del Pozuzo'),
('Huánuco', 'Puerto Inca', 'Honoria'),
('Huánuco', 'Puerto Inca', 'Tournavista'),
('Huánuco', 'Puerto Inca', 'Yuyapichis'),
('Huánuco', 'Lauricocha', 'Jesús'),
('Huánuco', 'Lauricocha', 'Baños'),
('Huánuco', 'Lauricocha', 'Jivia'),
('Huánuco', 'Lauricocha', 'Queropalca'),
('Huánuco', 'Lauricocha', 'Rondos'),
('Huánuco', 'Lauricocha', 'San Francisco de Asís'),
('Huánuco', 'Lauricocha', 'San Miguel de Cauri'),
('Huánuco', 'Yarowilca', 'Chavinillo'),
('Huánuco', 'Yarowilca', 'Cahuac'),
('Huánuco', 'Yarowilca', 'Chacabamba'),
('Huánuco', 'Yarowilca', 'Aparicio Pomares'),
('Huánuco', 'Yarowilca', 'Jacas Chico'),
('Huánuco', 'Yarowilca', 'Obas'),
('Huánuco', 'Yarowilca', 'Pampamarca'),
('Huánuco', 'Yarowilca', 'Choras'),
('Ica', 'Ica', 'Ica'),
('Ica', 'Ica', 'La Tinguiña'),
('Ica', 'Ica', 'Los Aquijes'),
('Ica', 'Ica', 'Ocucaje'),
('Ica', 'Ica', 'Pachacutec'),
('Ica', 'Ica', 'Parcona'),
('Ica', 'Ica', 'Pueblo Nuevo'),
('Ica', 'Ica', 'Salas'),
('Ica', 'Ica', 'San José de Los Molinos'),
('Ica', 'Ica', 'San Juan Bautista'),
('Ica', 'Ica', 'Santiago'),
('Ica', 'Ica', 'Subtanjalla'),
('Ica', 'Ica', 'Tate'),
('Ica', 'Ica', 'Yauca del Rosario'),
('Ica', 'Chincha', 'Chincha Alta'),
('Ica', 'Chincha', 'Alto Laran'),
('Ica', 'Chincha', 'Chavin'),
('Ica', 'Chincha', 'Chincha Baja'),
('Ica', 'Chincha', 'El Carmen'),
('Ica', 'Chincha', 'Grocio Prado'),
('Ica', 'Chincha', 'Pueblo Nuevo'),
('Ica', 'Chincha', 'San Juan de Yanac'),
('Ica', 'Chincha', 'San Pedro de Huacarpana'),
('Ica', 'Chincha', 'Sunampe'),
('Ica', 'Chincha', 'Tambo de Mora'),
('Ica', 'Nazca', 'Nasca'),
('Ica', 'Nazca', 'Changuillo'),
('Ica', 'Nazca', 'El Ingenio'),
('Ica', 'Nazca', 'Marcona'),
('Ica', 'Nazca', 'Vista Alegre'),
('Ica', 'Palpa', 'Palpa'),
('Ica', 'Palpa', 'Llipata'),
('Ica', 'Palpa', 'Río Grande'),
('Ica', 'Palpa', 'Santa Cruz'),
('Ica', 'Palpa', 'Tibillo'),
('Ica', 'Pisco', 'Pisco'),
('Ica', 'Pisco', 'Huancano'),
('Ica', 'Pisco', 'Humay'),
('Ica', 'Pisco', 'Independencia'),
('Ica', 'Pisco', 'Paracas'),
('Ica', 'Pisco', 'San Andrés'),
('Ica', 'Pisco', 'San Clemente'),
('Ica', 'Pisco', 'Tupac Amaru Inca'),
('Junín', 'Huancayo', 'Huancayo'),
('Junín', 'Huancayo', 'Carhuacallanga'),
('Junín', 'Huancayo', 'Chacapampa'),
('Junín', 'Huancayo', 'Chicche'),
('Junín', 'Huancayo', 'Chilca'),
('Junín', 'Huancayo', 'Chongos Alto'),
('Junín', 'Huancayo', 'Chupuro'),
('Junín', 'Huancayo', 'Colca'),
('Junín', 'Huancayo', 'Cullhuas'),
('Junín', 'Huancayo', 'El Tambo'),
('Junín', 'Huancayo', 'Huacrapuquio'),
('Junín', 'Huancayo', 'Hualhuas'),
('Junín', 'Huancayo', 'Huancan'),
('Junín', 'Huancayo', 'Huasicancha'),
('Junín', 'Huancayo', 'Huayucachi'),
('Junín', 'Huancayo', 'Ingenio'),
('Junín', 'Huancayo', 'Pariahuanca'),
('Junín', 'Huancayo', 'Pilcomayo'),
('Junín', 'Huancayo', 'Pucara'),
('Junín', 'Huancayo', 'Quichuay'),
('Junín', 'Huancayo', 'Quilcas'),
('Junín', 'Huancayo', 'San Agustín'),
('Junín', 'Huancayo', 'San Jerónimo de Tunan'),
('Junín', 'Huancayo', 'Saño'),
('Junín', 'Huancayo', 'Sapallanga'),
('Junín', 'Huancayo', 'Sicaya'),
('Junín', 'Huancayo', 'Santo Domingo de Acobamba'),
('Junín', 'Huancayo', 'Viques'),
('Junín', 'Concepción', 'Concepción'),
('Junín', 'Concepción', 'Aco'),
('Junín', 'Concepción', 'Andamarca'),
('Junín', 'Concepción', 'Chambara'),
('Junín', 'Concepción', 'Cochas'),
('Junín', 'Concepción', 'Comas'),
('Junín', 'Concepción', 'Heroínas Toledo'),
('Junín', 'Concepción', 'Manzanares'),
('Junín', 'Concepción', 'Mariscal Castilla'),
('Junín', 'Concepción', 'Matahuasi'),
('Junín', 'Concepción', 'Mito'),
('Junín', 'Concepción', 'Nueve de Julio'),
('Junín', 'Concepción', 'Orcotuna'),
('Junín', 'Concepción', 'San José de Quero'),
('Junín', 'Concepción', 'Santa Rosa de Ocopa'),
('Junín', 'Chanchamayo', 'Chanchamayo'),
('Junín', 'Chanchamayo', 'Perene'),
('Junín', 'Chanchamayo', 'Pichanaqui'),
('Junín', 'Chanchamayo', 'San Luis de Shuaro'),
('Junín', 'Chanchamayo', 'San Ramón'),
('Junín', 'Chanchamayo', 'Vitoc'),
('Junín', 'Jauja', 'Jauja'),
('Junín', 'Jauja', 'Acolla'),
('Junín', 'Jauja', 'Apata'),
('Junín', 'Jauja', 'Ataura'),
('Junín', 'Jauja', 'Canchayllo'),
('Junín', 'Jauja', 'Curicaca'),
('Junín', 'Jauja', 'El Mantaro'),
('Junín', 'Jauja', 'Huamali'),
('Junín', 'Jauja', 'Huaripampa'),
('Junín', 'Jauja', 'Huertas'),
('Junín', 'Jauja', 'Janjaillo'),
('Junín', 'Jauja', 'Julcán'),
('Junín', 'Jauja', 'Leonor Ordóñez'),
('Junín', 'Jauja', 'Llocllapampa'),
('Junín', 'Jauja', 'Marco'),
('Junín', 'Jauja', 'Masma'),
('Junín', 'Jauja', 'Masma Chicche'),
('Junín', 'Jauja', 'Molinos'),
('Junín', 'Jauja', 'Monobamba'),
('Junín', 'Jauja', 'Muqui'),
('Junín', 'Jauja', 'Muquiyauyo'),
('Junín', 'Jauja', 'Paca'),
('Junín', 'Jauja', 'Paccha'),
('Junín', 'Jauja', 'Pancan'),
('Junín', 'Jauja', 'Parco'),
('Junín', 'Jauja', 'Pomacancha'),
('Junín', 'Jauja', 'Ricran'),
('Junín', 'Jauja', 'San Lorenzo'),
('Junín', 'Jauja', 'San Pedro de Chunan'),
('Junín', 'Jauja', 'Sausa'),
('Junín', 'Jauja', 'Sincos'),
('Junín', 'Jauja', 'Tunan Marca'),
('Junín', 'Jauja', 'Yauli'),
('Junín', 'Jauja', 'Yauyos'),
('Junín', 'Junín', 'Junin'),
('Junín', 'Junín', 'Carhuamayo'),
('Junín', 'Junín', 'Ondores'),
('Junín', 'Junín', 'Ulcumayo'),
('Junín', 'Satipo', 'Satipo'),
('Junín', 'Satipo', 'Coviriali'),
('Junín', 'Satipo', 'Llaylla'),
('Junín', 'Satipo', 'Mazamari'),
('Junín', 'Satipo', 'Pampa Hermosa'),
('Junín', 'Satipo', 'Pangoa'),
('Junín', 'Satipo', 'Río Negro'),
('Junín', 'Satipo', 'Río Tambo'),
('Junín', 'Satipo', 'Vizcatan del Ene'),
('Junín', 'Tarma', 'Tarma'),
('Junín', 'Tarma', 'Acobamba'),
('Junín', 'Tarma', 'Huaricolca'),
('Junín', 'Tarma', 'Huasahuasi'),
('Junín', 'Tarma', 'La Unión'),
('Junín', 'Tarma', 'Palca'),
('Junín', 'Tarma', 'Palcamayo'),
('Junín', 'Tarma', 'San Pedro de Cajas'),
('Junín', 'Tarma', 'Tapo'),
('Junín', 'Yauli', 'La Oroya'),
('Junín', 'Yauli', 'Chacapalpa'),
('Junín', 'Yauli', 'Huay-Huay'),
('Junín', 'Yauli', 'Marcapomacocha'),
('Junín', 'Yauli', 'Morococha'),
('Junín', 'Yauli', 'Paccha'),
('Junín', 'Yauli', 'Santa Bárbara de Carhuacayan'),
('Junín', 'Yauli', 'Santa Rosa de Sacco'),
('Junín', 'Yauli', 'Suitucancha'),
('Junín', 'Yauli', 'Yauli'),
('Junín', 'Chupaca', 'Chupaca'),
('Junín', 'Chupaca', 'Ahuac'),
('Junín', 'Chupaca', 'Chongos Bajo'),
('Junín', 'Chupaca', 'Huachac'),
('Junín', 'Chupaca', 'Huamancaca Chico'),
('Junín', 'Chupaca', 'San Juan de Iscos'),
('Junín', 'Chupaca', 'San Juan de Jarpa'),
('Junín', 'Chupaca', 'Tres de Diciembre'),
('Junín', 'Chupaca', 'Yanacancha'),
('La Libertad', 'Trujillo', 'Trujillo'),
('La Libertad', 'Trujillo', 'El Porvenir'),
('La Libertad', 'Trujillo', 'Florencia de Mora'),
('La Libertad', 'Trujillo', 'Huanchaco'),
('La Libertad', 'Trujillo', 'La Esperanza'),
('La Libertad', 'Trujillo', 'Laredo'),
('La Libertad', 'Trujillo', 'Moche'),
('La Libertad', 'Trujillo', 'Poroto'),
('La Libertad', 'Trujillo', 'Salaverry'),
('La Libertad', 'Trujillo', 'Simbal'),
('La Libertad', 'Trujillo', 'Victor Larco Herrera'),
('La Libertad', 'Ascope', 'Ascope'),
('La Libertad', 'Ascope', 'Chicama'),
('La Libertad', 'Ascope', 'Chocope'),
('La Libertad', 'Ascope', 'Magdalena de Cao'),
('La Libertad', 'Ascope', 'Paijan'),
('La Libertad', 'Ascope', 'Rázuri'),
('La Libertad', 'Ascope', 'Santiago de Cao'),
('La Libertad', 'Ascope', 'Casa Grande'),
('La Libertad', 'Bolívar', 'Bolívar'),
('La Libertad', 'Bolívar', 'Bambamarca'),
('La Libertad', 'Bolívar', 'Condormarca'),
('La Libertad', 'Bolívar', 'Longotea'),
('La Libertad', 'Bolívar', 'Uchumarca'),
('La Libertad', 'Bolívar', 'Ucuncha'),
('La Libertad', 'Chepén', 'Chepen'),
('La Libertad', 'Chepén', 'Pacanga'),
('La Libertad', 'Chepén', 'Pueblo Nuevo'),
('La Libertad', 'Julcán', 'Julcan'),
('La Libertad', 'Julcán', 'Calamarca'),
('La Libertad', 'Julcán', 'Carabamba'),
('La Libertad', 'Julcán', 'Huaso'),
('La Libertad', 'Otuzco', 'Otuzco'),
('La Libertad', 'Otuzco', 'Agallpampa'),
('La Libertad', 'Otuzco', 'Charat'),
('La Libertad', 'Otuzco', 'Huaranchal'),
('La Libertad', 'Otuzco', 'La Cuesta'),
('La Libertad', 'Otuzco', 'Mache'),
('La Libertad', 'Otuzco', 'Paranday'),
('La Libertad', 'Otuzco', 'Salpo'),
('La Libertad', 'Otuzco', 'Sinsicap'),
('La Libertad', 'Otuzco', 'Usquil'),
('La Libertad', 'Pacasmayo', 'San Pedro de Lloc'),
('La Libertad', 'Pacasmayo', 'Guadalupe'),
('La Libertad', 'Pacasmayo', 'Jequetepeque'),
('La Libertad', 'Pacasmayo', 'Pacasmayo'),
('La Libertad', 'Pacasmayo', 'San José'),
('La Libertad', 'Pataz', 'Tayabamba'),
('La Libertad', 'Pataz', 'Buldibuyo'),
('La Libertad', 'Pataz', 'Chillia'),
('La Libertad', 'Pataz', 'Huancaspata'),
('La Libertad', 'Pataz', 'Huaylillas'),
('La Libertad', 'Pataz', 'Huayo'),
('La Libertad', 'Pataz', 'Ongon'),
('La Libertad', 'Pataz', 'Parcoy'),
('La Libertad', 'Pataz', 'Pataz'),
('La Libertad', 'Pataz', 'Pias'),
('La Libertad', 'Pataz', 'Santiago de Challas'),
('La Libertad', 'Pataz', 'Taurija'),
('La Libertad', 'Pataz', 'Urpay'),
('La Libertad', 'Sánchez Carrión', 'Huamachuco'),
('La Libertad', 'Sánchez Carrión', 'Chugay'),
('La Libertad', 'Sánchez Carrión', 'Cochorco'),
('La Libertad', 'Sánchez Carrión', 'Curgos'),
('La Libertad', 'Sánchez Carrión', 'Marcabal'),
('La Libertad', 'Sánchez Carrión', 'Sanagoran'),
('La Libertad', 'Sánchez Carrión', 'Sarin'),
('La Libertad', 'Sánchez Carrión', 'Sartimbamba'),
('La Libertad', 'Santiago de Chuco', 'Santiago de Chuco'),
('La Libertad', 'Santiago de Chuco', 'Angasmarca'),
('La Libertad', 'Santiago de Chuco', 'Cachicadan'),
('La Libertad', 'Santiago de Chuco', 'Mollebamba'),
('La Libertad', 'Santiago de Chuco', 'Mollepata'),
('La Libertad', 'Santiago de Chuco', 'Quiruvilca'),
('La Libertad', 'Santiago de Chuco', 'Santa Cruz de Chuca'),
('La Libertad', 'Santiago de Chuco', 'Sitabamba'),
('La Libertad', 'Gran Chimú', 'Cascas'),
('La Libertad', 'Gran Chimú', 'Lucma'),
('La Libertad', 'Gran Chimú', 'Marmot'),
('La Libertad', 'Gran Chimú', 'Sayapullo'),
('La Libertad', 'Virú', 'Viru'),
('La Libertad', 'Virú', 'Chao'),
('La Libertad', 'Virú', 'Guadalupito'),
('Lambayeque', 'Chiclayo', 'Chiclayo'),
('Lambayeque', 'Chiclayo', 'Chongoyape'),
('Lambayeque', 'Chiclayo', 'Eten'),
('Lambayeque', 'Chiclayo', 'Eten Puerto'),
('Lambayeque', 'Chiclayo', 'José Leonardo Ortiz'),
('Lambayeque', 'Chiclayo', 'La Victoria'),
('Lambayeque', 'Chiclayo', 'Lagunas'),
('Lambayeque', 'Chiclayo', 'Monsefu'),
('Lambayeque', 'Chiclayo', 'Nueva Arica'),
('Lambayeque', 'Chiclayo', 'Oyotun'),
('Lambayeque', 'Chiclayo', 'Picsi'),
('Lambayeque', 'Chiclayo', 'Pimentel'),
('Lambayeque', 'Chiclayo', 'Reque'),
('Lambayeque', 'Chiclayo', 'Santa Rosa'),
('Lambayeque', 'Chiclayo', 'Saña'),
('Lambayeque', 'Chiclayo', 'Cayalti'),
('Lambayeque', 'Chiclayo', 'Patapo'),
('Lambayeque', 'Chiclayo', 'Pomalca'),
('Lambayeque', 'Chiclayo', 'Pucala'),
('Lambayeque', 'Chiclayo', 'Tuman'),
('Lambayeque', 'Ferreñafe', 'Ferreñafe'),
('Lambayeque', 'Ferreñafe', 'Cañaris'),
('Lambayeque', 'Ferreñafe', 'Incahuasi'),
('Lambayeque', 'Ferreñafe', 'Manuel Antonio Mesones Muro'),
('Lambayeque', 'Ferreñafe', 'Pitipo'),
('Lambayeque', 'Ferreñafe', 'Pueblo Nuevo'),
('Lambayeque', 'Lambayeque', 'Lambayeque'),
('Lambayeque', 'Lambayeque', 'Chochope'),
('Lambayeque', 'Lambayeque', 'Illimo'),
('Lambayeque', 'Lambayeque', 'Jayanca'),
('Lambayeque', 'Lambayeque', 'Mochumi'),
('Lambayeque', 'Lambayeque', 'Morrope'),
('Lambayeque', 'Lambayeque', 'Motupe'),
('Lambayeque', 'Lambayeque', 'Olmos'),
('Lambayeque', 'Lambayeque', 'Pacora'),
('Lambayeque', 'Lambayeque', 'Salas'),
('Lambayeque', 'Lambayeque', 'San José'),
('Lambayeque', 'Lambayeque', 'Tucume'),
('Lima', 'Lima', 'Lima'),
('Lima', 'Lima', 'Ancón'),
('Lima', 'Lima', 'Ate'),
('Lima', 'Lima', 'Barranco'),
('Lima', 'Lima', 'Breña'),
('Lima', 'Lima', 'Carabayllo'),
('Lima', 'Lima', 'Chaclacayo'),
('Lima', 'Lima', 'Chorrillos'),
('Lima', 'Lima', 'Cieneguilla'),
('Lima', 'Lima', 'Comas'),
('Lima', 'Lima', 'El Agustino'),
('Lima', 'Lima', 'Independencia'),
('Lima', 'Lima', 'Jesús María'),
('Lima', 'Lima', 'La Molina'),
('Lima', 'Lima', 'La Victoria'),
('Lima', 'Lima', 'Lince'),
('Lima', 'Lima', 'Los Olivos'),
('Lima', 'Lima', 'Lurigancho'),
('Lima', 'Lima', 'Lurin'),
('Lima', 'Lima', 'Magdalena del Mar'),
('Lima', 'Lima', 'Pueblo Libre'),
('Lima', 'Lima', 'Miraflores'),
('Lima', 'Lima', 'Pachacamac'),
('Lima', 'Lima', 'Pucusana'),
('Lima', 'Lima', 'Puente Piedra'),
('Lima', 'Lima', 'Punta Hermosa'),
('Lima', 'Lima', 'Punta Negra'),
('Lima', 'Lima', 'Rímac'),
('Lima', 'Lima', 'San Bartolo'),
('Lima', 'Lima', 'San Borja'),
('Lima', 'Lima', 'San Isidro'),
('Lima', 'Lima', 'San Juan de Lurigancho'),
('Lima', 'Lima', 'San Juan de Miraflores'),
('Lima', 'Lima', 'San Luis'),
('Lima', 'Lima', 'San Martín de Porres'),
('Lima', 'Lima', 'San Miguel'),
('Lima', 'Lima', 'Santa Anita'),
('Lima', 'Lima', 'Santa María del Mar'),
('Lima', 'Lima', 'Santa Rosa'),
('Lima', 'Lima', 'Santiago de Surco'),
('Lima', 'Lima', 'Surquillo'),
('Lima', 'Lima', 'Villa El Salvador'),
('Lima', 'Lima', 'Villa María del Triunfo'),
('Lima', 'Barranca', 'Barranca'),
('Lima', 'Barranca', 'Paramonga'),
('Lima', 'Barranca', 'Pativilca'),
('Lima', 'Barranca', 'Supe'),
('Lima', 'Barranca', 'Supe Puerto'),
('Lima', 'Cajatambo', 'Cajatambo'),
('Lima', 'Cajatambo', 'Copa'),
('Lima', 'Cajatambo', 'Gorgor'),
('Lima', 'Cajatambo', 'Huancapon'),
('Lima', 'Cajatambo', 'Manas'),
('Lima', 'Canta', 'Canta'),
('Lima', 'Canta', 'Arahuay'),
('Lima', 'Canta', 'Huamantanga'),
('Lima', 'Canta', 'Huaros'),
('Lima', 'Canta', 'Lachaqui'),
('Lima', 'Canta', 'San Buenaventura'),
('Lima', 'Canta', 'Santa Rosa de Quives'),
('Lima', 'Cañete', 'San Vicente de Cañete'),
('Lima', 'Cañete', 'Asia'),
('Lima', 'Cañete', 'Calango'),
('Lima', 'Cañete', 'Cerro Azul'),
('Lima', 'Cañete', 'Chilca'),
('Lima', 'Cañete', 'Coayllo'),
('Lima', 'Cañete', 'Imperial'),
('Lima', 'Cañete', 'Lunahuana'),
('Lima', 'Cañete', 'Mala'),
('Lima', 'Cañete', 'Nuevo Imperial'),
('Lima', 'Cañete', 'Pacaran'),
('Lima', 'Cañete', 'Quilmana'),
('Lima', 'Cañete', 'San Antonio'),
('Lima', 'Cañete', 'San Luis'),
('Lima', 'Cañete', 'Santa Cruz de Flores'),
('Lima', 'Cañete', 'Zúñiga'),
('Lima', 'Huaral', 'Huaral'),
('Lima', 'Huaral', 'Atavillos Alto'),
('Lima', 'Huaral', 'Atavillos Bajo'),
('Lima', 'Huaral', 'Aucallama'),
('Lima', 'Huaral', 'Chancay'),
('Lima', 'Huaral', 'Ihuari'),
('Lima', 'Huaral', 'Lampian'),
('Lima', 'Huaral', 'Pacaraos'),
('Lima', 'Huaral', 'San Miguel de Acos'),
('Lima', 'Huaral', 'Santa Cruz de Andamarca'),
('Lima', 'Huaral', 'Sumbilca'),
('Lima', 'Huaral', 'Veintisiete de Noviembre'),
('Lima', 'Huarochirí', 'Matucana'),
('Lima', 'Huarochirí', 'Antioquia'),
('Lima', 'Huarochirí', 'Callahuanca'),
('Lima', 'Huarochirí', 'Carampoma'),
('Lima', 'Huarochirí', 'Chicla'),
('Lima', 'Huarochirí', 'Cuenca'),
('Lima', 'Huarochirí', 'Huachupampa'),
('Lima', 'Huarochirí', 'Huanza'),
('Lima', 'Huarochirí', 'Huarochiri'),
('Lima', 'Huarochirí', 'Lahuaytambo'),
('Lima', 'Huarochirí', 'Langa'),
('Lima', 'Huarochirí', 'Laraos'),
('Lima', 'Huarochirí', 'Mariatana'),
('Lima', 'Huarochirí', 'Ricardo Palma'),
('Lima', 'Huarochirí', 'San Andrés de Tupicocha'),
('Lima', 'Huarochirí', 'San Antonio'),
('Lima', 'Huarochirí', 'San Bartolomé'),
('Lima', 'Huarochirí', 'San Damian'),
('Lima', 'Huarochirí', 'San Juan de Iris'),
('Lima', 'Huarochirí', 'San Juan de Tantaranche'),
('Lima', 'Huarochirí', 'San Lorenzo de Quinti'),
('Lima', 'Huarochirí', 'San Mateo'),
('Lima', 'Huarochirí', 'San Mateo de Otao'),
('Lima', 'Huarochirí', 'San Pedro de Casta'),
('Lima', 'Huarochirí', 'San Pedro de Huancayre'),
('Lima', 'Huarochirí', 'Sangallaya'),
('Lima', 'Huarochirí', 'Santa Cruz de Cocachacra'),
('Lima', 'Huarochirí', 'Santa Eulalia'),
('Lima', 'Huarochirí', 'Santiago de Anchucaya'),
('Lima', 'Huarochirí', 'Santiago de Tuna'),
('Lima', 'Huarochirí', 'Santo Domingo de Los Olleros'),
('Lima', 'Huarochirí', 'Surco'),
('Lima', 'Huaura', 'Huacho'),
('Lima', 'Huaura', 'Ambar'),
('Lima', 'Huaura', 'Caleta de Carquin'),
('Lima', 'Huaura', 'Checras'),
('Lima', 'Huaura', 'Hualmay'),
('Lima', 'Huaura', 'Huaura'),
('Lima', 'Huaura', 'Leoncio Prado'),
('Lima', 'Huaura', 'Paccho'),
('Lima', 'Huaura', 'Santa Leonor'),
('Lima', 'Huaura', 'Santa María'),
('Lima', 'Huaura', 'Sayan'),
('Lima', 'Huaura', 'Vegueta'),
('Lima', 'Oyón', 'Oyon'),
('Lima', 'Oyón', 'Andajes'),
('Lima', 'Oyón', 'Caujul'),
('Lima', 'Oyón', 'Cochamarca'),
('Lima', 'Oyón', 'Navan'),
('Lima', 'Oyón', 'Pachangara'),
('Lima', 'Yauyos', 'Yauyos'),
('Lima', 'Yauyos', 'Alis'),
('Lima', 'Yauyos', 'Allauca'),
('Lima', 'Yauyos', 'Ayaviri'),
('Lima', 'Yauyos', 'Azángaro'),
('Lima', 'Yauyos', 'Cacra'),
('Lima', 'Yauyos', 'Carania'),
('Lima', 'Yauyos', 'Catahuasi'),
('Lima', 'Yauyos', 'Chocos'),
('Lima', 'Yauyos', 'Cochas'),
('Lima', 'Yauyos', 'Colonia'),
('Lima', 'Yauyos', 'Hongos'),
('Lima', 'Yauyos', 'Huampara'),
('Lima', 'Yauyos', 'Huancaya'),
('Lima', 'Yauyos', 'Huangascar'),
('Lima', 'Yauyos', 'Huantan'),
('Lima', 'Yauyos', 'Huañec'),
('Lima', 'Yauyos', 'Laraos'),
('Lima', 'Yauyos', 'Lincha'),
('Lima', 'Yauyos', 'Madean'),
('Lima', 'Yauyos', 'Miraflores'),
('Lima', 'Yauyos', 'Omas'),
('Lima', 'Yauyos', 'Putinza'),
('Lima', 'Yauyos', 'Quinches'),
('Lima', 'Yauyos', 'Quinocay'),
('Lima', 'Yauyos', 'San Joaquín'),
('Lima', 'Yauyos', 'San Pedro de Pilas'),
('Lima', 'Yauyos', 'Tanta'),
('Lima', 'Yauyos', 'Tauripampa'),
('Lima', 'Yauyos', 'Tomas'),
('Lima', 'Yauyos', 'Tupe'),
('Lima', 'Yauyos', 'Viñac'),
('Lima', 'Yauyos', 'Vitis'),
('Loreto', 'Maynas', 'Iquitos'),
('Loreto', 'Maynas', 'Alto Nanay'),
('Loreto', 'Maynas', 'Fernando Lores'),
('Loreto', 'Maynas', 'Indiana'),
('Loreto', 'Maynas', 'Las Amazonas'),
('Loreto', 'Maynas', 'Mazan'),
('Loreto', 'Maynas', 'Napo'),
('Loreto', 'Maynas', 'Punchana'),
('Loreto', 'Maynas', 'Torres Causana'),
('Loreto', 'Maynas', 'Belén'),
('Loreto', 'Maynas', 'San Juan Bautista'),
('Loreto', 'Alto Amazonas', 'Yurimaguas'),
('Loreto', 'Alto Amazonas', 'Balsapuerto'),
('Loreto', 'Alto Amazonas', 'Jeberos'),
('Loreto', 'Alto Amazonas', 'Lagunas'),
('Loreto', 'Alto Amazonas', 'Santa Cruz'),
('Loreto', 'Alto Amazonas', 'Teniente Cesar López Rojas'),
('Loreto', 'Loreto', 'Nauta'),
('Loreto', 'Loreto', 'Parinari'),
('Loreto', 'Loreto', 'Tigre'),
('Loreto', 'Loreto', 'Trompeteros'),
('Loreto', 'Loreto', 'Urarinas'),
('Loreto', 'Mariscal Ramón Castilla', 'Ramón Castilla'),
('Loreto', 'Mariscal Ramón Castilla', 'Pebas'),
('Loreto', 'Mariscal Ramón Castilla', 'Yavari'),
('Loreto', 'Mariscal Ramón Castilla', 'San Pablo'),
('Loreto', 'Requena', 'Requena'),
('Loreto', 'Requena', 'Alto Tapiche'),
('Loreto', 'Requena', 'Capelo'),
('Loreto', 'Requena', 'Emilio San Martín'),
('Loreto', 'Requena', 'Maquia'),
('Loreto', 'Requena', 'Puinahua'),
('Loreto', 'Requena', 'Saquena'),
('Loreto', 'Requena', 'Soplin'),
('Loreto', 'Requena', 'Tapiche'),
('Loreto', 'Requena', 'Jenaro Herrera'),
('Loreto', 'Requena', 'Yaquerana'),
('Loreto', 'Ucayali', 'Contamana'),
('Loreto', 'Ucayali', 'Inahuaya'),
('Loreto', 'Ucayali', 'Padre Márquez'),
('Loreto', 'Ucayali', 'Pampa Hermosa'),
('Loreto', 'Ucayali', 'Sarayacu'),
('Loreto', 'Ucayali', 'Vargas Guerra'),
('Loreto', 'Datem del Marañón', 'Barranca'),
('Loreto', 'Datem del Marañón', 'Cahuapanas'),
('Loreto', 'Datem del Marañón', 'Manseriche'),
('Loreto', 'Datem del Marañón', 'Morona'),
('Loreto', 'Datem del Marañón', 'Pastaza'),
('Loreto', 'Datem del Marañón', 'Andoas'),
('Loreto', 'Putumayo', 'Putumayo'),
('Loreto', 'Putumayo', 'Rosa Panduro'),
('Loreto', 'Putumayo', 'Teniente Manuel Clavero'),
('Loreto', 'Putumayo', 'Yaguas'),
('Madre de Dios', 'Tambopata', 'Tambopata'),
('Madre de Dios', 'Tambopata', 'Inambari'),
('Madre de Dios', 'Tambopata', 'Las Piedras'),
('Madre de Dios', 'Tambopata', 'Laberinto'),
('Madre de Dios', 'Manu', 'Manu'),
('Madre de Dios', 'Manu', 'Fitzcarrald'),
('Madre de Dios', 'Manu', 'Madre de Dios'),
('Madre de Dios', 'Manu', 'Huepetuhe'),
('Madre de Dios', 'Tahuamanu', 'Iñapari'),
('Madre de Dios', 'Tahuamanu', 'Iberia'),
('Madre de Dios', 'Tahuamanu', 'Tahuamanu'),
('Moquegua', 'Mariscal Nieto', 'Moquegua'),
('Moquegua', 'Mariscal Nieto', 'Carumas'),
('Moquegua', 'Mariscal Nieto', 'Cuchumbaya'),
('Moquegua', 'Mariscal Nieto', 'Samegua'),
('Moquegua', 'Mariscal Nieto', 'San Cristóbal'),
('Moquegua', 'Mariscal Nieto', 'Torata'),
('Moquegua', 'General Sánchez Cerro', 'Omate'),
('Moquegua', 'General Sánchez Cerro', 'Chojata'),
('Moquegua', 'General Sánchez Cerro', 'Coalaque'),
('Moquegua', 'General Sánchez Cerro', 'Ichuña'),
('Moquegua', 'General Sánchez Cerro', 'La Capilla'),
('Moquegua', 'General Sánchez Cerro', 'Lloque'),
('Moquegua', 'General Sánchez Cerro', 'Matalaque'),
('Moquegua', 'General Sánchez Cerro', 'Puquina'),
('Moquegua', 'General Sánchez Cerro', 'Quinistaquillas'),
('Moquegua', 'General Sánchez Cerro', 'Ubinas'),
('Moquegua', 'General Sánchez Cerro', 'Yunga'),
('Moquegua', 'Ilo', 'Ilo'),
('Moquegua', 'Ilo', 'El Algarrobal'),
('Moquegua', 'Ilo', 'Pacocha'),
('Pasco', 'Pasco', 'Chaupimarca'),
('Pasco', 'Pasco', 'Huachon'),
('Pasco', 'Pasco', 'Huariaca'),
('Pasco', 'Pasco', 'Huayllay'),
('Pasco', 'Pasco', 'Ninacaca'),
('Pasco', 'Pasco', 'Pallanchacra'),
('Pasco', 'Pasco', 'Paucartambo'),
('Pasco', 'Pasco', 'San Francisco de Asís de Yarusyacan'),
('Pasco', 'Pasco', 'Simon Bolívar'),
('Pasco', 'Pasco', 'Ticlacayan'),
('Pasco', 'Pasco', 'Tinyahuarco'),
('Pasco', 'Pasco', 'Vicco'),
('Pasco', 'Pasco', 'Yanacancha'),
('Pasco', 'Daniel Alcides Carrión', 'Yanahuanca'),
('Pasco', 'Daniel Alcides Carrión', 'Chacayan'),
('Pasco', 'Daniel Alcides Carrión', 'Goyllarisquizga'),
('Pasco', 'Daniel Alcides Carrión', 'Paucar'),
('Pasco', 'Daniel Alcides Carrión', 'San Pedro de Pillao'),
('Pasco', 'Daniel Alcides Carrión', 'Santa Ana de Tusi'),
('Pasco', 'Daniel Alcides Carrión', 'Tapuc'),
('Pasco', 'Daniel Alcides Carrión', 'Vilcabamba'),
('Pasco', 'Oxapampa', 'Oxapampa'),
('Pasco', 'Oxapampa', 'Chontabamba'),
('Pasco', 'Oxapampa', 'Huancabamba'),
('Pasco', 'Oxapampa', 'Palcazu'),
('Pasco', 'Oxapampa', 'Pozuzo'),
('Pasco', 'Oxapampa', 'Puerto Bermúdez'),
('Pasco', 'Oxapampa', 'Villa Rica'),
('Pasco', 'Oxapampa', 'Constitución'),
('Piura', 'Piura', 'Piura'),
('Piura', 'Piura', 'Castilla'),
('Piura', 'Piura', 'Atacaos'),
('Piura', 'Piura', 'Cura Mori'),
('Piura', 'Piura', 'El Tallan'),
('Piura', 'Piura', 'La Arena'),
('Piura', 'Piura', 'La Unión'),
('Piura', 'Piura', 'Las Lomas'),
('Piura', 'Piura', 'Tambo Grande'),
('Piura', 'Piura', 'Veintiseis de Octubre'),
('Piura', 'Ayabaca', 'Ayabaca'),
('Piura', 'Ayabaca', 'Frias'),
('Piura', 'Ayabaca', 'Jilili'),
('Piura', 'Ayabaca', 'Lagunas'),
('Piura', 'Ayabaca', 'Montero'),
('Piura', 'Ayabaca', 'Pacaipampa'),
('Piura', 'Ayabaca', 'Paimas'),
('Piura', 'Ayabaca', 'Sapillica'),
('Piura', 'Ayabaca', 'Sicchez'),
('Piura', 'Ayabaca', 'Suyo'),
('Piura', 'Huancabamba', 'Huancabamba'),
('Piura', 'Huancabamba', 'Canchaque'),
('Piura', 'Huancabamba', 'El Carmen de la Frontera'),
('Piura', 'Huancabamba', 'Huarmaca'),
('Piura', 'Huancabamba', 'Lalaquiz'),
('Piura', 'Huancabamba', 'San Miguel de El Faique'),
('Piura', 'Huancabamba', 'Sondor'),
('Piura', 'Huancabamba', 'Sondorillo'),
('Piura', 'Morropón', 'Chulucanas'),
('Piura', 'Morropón', 'Buenos Aires'),
('Piura', 'Morropón', 'Chalaco'),
('Piura', 'Morropón', 'La Matanza'),
('Piura', 'Morropón', 'Morropon'),
('Piura', 'Morropón', 'Salitral'),
('Piura', 'Morropón', 'San Juan de Bigote'),
('Piura', 'Morropón', 'Santa Catalina de Mossa'),
('Piura', 'Morropón', 'Santo Domingo'),
('Piura', 'Morropón', 'Yamango'),
('Piura', 'Paita', 'Paita'),
('Piura', 'Paita', 'Amotape'),
('Piura', 'Paita', 'Arenal'),
('Piura', 'Paita', 'Colan'),
('Piura', 'Paita', 'La Huaca'),
('Piura', 'Paita', 'Tamarindo'),
('Piura', 'Paita', 'Vichayal'),
('Piura', 'Sullana', 'Sullana'),
('Piura', 'Sullana', 'Bellavista'),
('Piura', 'Sullana', 'Ignacio Escudero'),
('Piura', 'Sullana', 'Lancones'),
('Piura', 'Sullana', 'Marcavelica'),
('Piura', 'Sullana', 'Miguel Checa'),
('Piura', 'Sullana', 'Querecotillo'),
('Piura', 'Sullana', 'Salitral'),
('Piura', 'Talara', 'Pariñas'),
('Piura', 'Talara', 'El Alto'),
('Piura', 'Talara', 'La Brea'),
('Piura', 'Talara', 'Lobitos'),
('Piura', 'Talara', 'Los Organos'),
('Piura', 'Talara', 'Mancora'),
('Piura', 'Sechura', 'Sechura'),
('Piura', 'Sechura', 'Bellavista de la Unión'),
('Piura', 'Sechura', 'Bernal'),
('Piura', 'Sechura', 'Cristo Nos Valga'),
('Piura', 'Sechura', 'Vice'),
('Piura', 'Sechura', 'Rinconada Llicuar'),
('Puno', 'Puno', 'Puno'),
('Puno', 'Puno', 'Acora'),
('Puno', 'Puno', 'Amantani'),
('Puno', 'Puno', 'Atuncolla'),
('Puno', 'Puno', 'Capachica'),
('Puno', 'Puno', 'Chucuito'),
('Puno', 'Puno', 'Coata'),
('Puno', 'Puno', 'Huata'),
('Puno', 'Puno', 'Mañazo'),
('Puno', 'Puno', 'Paucarcolla'),
('Puno', 'Puno', 'Pichacani'),
('Puno', 'Puno', 'Plateria'),
('Puno', 'Puno', 'San Antonio'),
('Puno', 'Puno', 'Tiquillaca'),
('Puno', 'Puno', 'Vilque'),
('Puno', 'Azángaro', 'Azángaro'),
('Puno', 'Azángaro', 'Achaya'),
('Puno', 'Azángaro', 'Arapa'),
('Puno', 'Azángaro', 'Asillo'),
('Puno', 'Azángaro', 'Caminaca'),
('Puno', 'Azángaro', 'Chupa'),
('Puno', 'Azángaro', 'José Domingo Choquehuanca'),
('Puno', 'Azángaro', 'Muñani'),
('Puno', 'Azángaro', 'Potoni'),
('Puno', 'Azángaro', 'Saman'),
('Puno', 'Azángaro', 'San Anton'),
('Puno', 'Azángaro', 'San José'),
('Puno', 'Azángaro', 'San Juan de Salinas'),
('Puno', 'Azángaro', 'Santiago de Pupuja'),
('Puno', 'Azángaro', 'Tirapata'),
('Puno', 'Carabaya', 'Macusani'),
('Puno', 'Carabaya', 'Ajoyani'),
('Puno', 'Carabaya', 'Ayapata'),
('Puno', 'Carabaya', 'Coasa'),
('Puno', 'Carabaya', 'Corani'),
('Puno', 'Carabaya', 'Crucero'),
('Puno', 'Carabaya', 'Ituata'),
('Puno', 'Carabaya', 'Ollachea'),
('Puno', 'Carabaya', 'San Gaban'),
('Puno', 'Carabaya', 'Usicayos'),
('Puno', 'Chucuito', '08'),
('Puno', 'Chucuito', 'Desaguadero'),
('Puno', 'Chucuito', 'Huacullani'),
('Puno', 'Chucuito', 'Kelluyo'),
('Puno', 'Chucuito', 'Pisacoma'),
('Puno', 'Chucuito', 'Pomata'),
('Puno', 'Chucuito', 'Zepita'),
('Puno', 'El Collao', 'Ilave'),
('Puno', 'El Collao', 'Capazo'),
('Puno', 'El Collao', 'Pilcuyo'),
('Puno', 'El Collao', 'Santa Rosa'),
('Puno', 'El Collao', 'Conduriri'),
('Puno', 'Huancané', 'Huancane'),
('Puno', 'Huancané', 'Cojata'),
('Puno', 'Huancané', 'Huatasani'),
('Puno', 'Huancané', 'Inchupalla'),
('Puno', 'Huancané', 'Pusi'),
('Puno', 'Huancané', 'Rosaspata'),
('Puno', 'Huancané', 'Taraco'),
('Puno', 'Huancané', 'Vilque Chico'),
('Puno', 'Lampa', 'Lampa'),
('Puno', 'Lampa', 'Cabanilla'),
('Puno', 'Lampa', 'Calapuja'),
('Puno', 'Lampa', 'Nicasio'),
('Puno', 'Lampa', 'Ocuviri'),
('Puno', 'Lampa', 'Palca'),
('Puno', 'Lampa', 'Paratia'),
('Puno', 'Lampa', 'Pucara'),
('Puno', 'Lampa', 'Santa Lucia'),
('Puno', 'Lampa', 'Vilavila'),
('Puno', 'Melgar', 'Ayaviri'),
('Puno', 'Melgar', 'Antauta'),
('Puno', 'Melgar', 'Cupi'),
('Puno', 'Melgar', 'Llalli'),
('Puno', 'Melgar', 'Macari'),
('Puno', 'Melgar', 'Nuñoa'),
('Puno', 'Melgar', 'Orurillo'),
('Puno', 'Melgar', 'Santa Rosa'),
('Puno', 'Melgar', 'Umachiri'),
('Puno', 'Moho', 'Moho'),
('Puno', 'Moho', 'Conima'),
('Puno', 'Moho', 'Huayrapata'),
('Puno', 'Moho', 'Tilali'),
('Puno', 'San Antonio de Putina', 'Putina'),
('Puno', 'San Antonio de Putina', 'Ananea'),
('Puno', 'San Antonio de Putina', 'Pedro Vilca Apaza'),
('Puno', 'San Antonio de Putina', 'Quilcapuncu'),
('Puno', 'San Antonio de Putina', 'Sina'),
('Puno', 'San Román', 'Juliaca'),
('Puno', 'San Román', 'Cabana'),
('Puno', 'San Román', 'Cabanillas'),
('Puno', 'San Román', 'Caracoto'),
('Puno', 'Sandia', 'Sandia'),
('Puno', 'Sandia', 'Cuyocuyo'),
('Puno', 'Sandia', 'Limbani'),
('Puno', 'Sandia', 'Patambuco'),
('Puno', 'Sandia', 'Phara'),
('Puno', 'Sandia', 'Quiaca'),
('Puno', 'Sandia', 'San Juan del Oro'),
('Puno', 'Sandia', 'Yanahuaya'),
('Puno', 'Sandia', 'Alto Inambari'),
('Puno', 'Sandia', 'San Pedro de Putina Punco'),
('Puno', 'Yunguyo', 'Yunguyo'),
('Puno', 'Yunguyo', 'Anapia'),
('Puno', 'Yunguyo', 'Copani'),
('Puno', 'Yunguyo', 'Cuturapi'),
('Puno', 'Yunguyo', 'Ollaraya'),
('Puno', 'Yunguyo', 'Tinicachi'),
('Puno', 'Yunguyo', 'Unicachi'),
('San Martín', 'Moyobamba', 'Moyobamba'),
('San Martín', 'Moyobamba', 'Calzada'),
('San Martín', 'Moyobamba', 'Habana'),
('San Martín', 'Moyobamba', 'Jepelacio'),
('San Martín', 'Moyobamba', 'Soritor'),
('San Martín', 'Moyobamba', 'Yantalo'),
('San Martín', 'Bellavista', 'Bellavista'),
('San Martín', 'Bellavista', 'Alto Biavo'),
('San Martín', 'Bellavista', 'Bajo Biavo'),
('San Martín', 'Bellavista', 'Huallaga'),
('San Martín', 'Bellavista', 'San Pablo'),
('San Martín', 'Bellavista', 'San Rafael'),
('San Martín', 'El Dorado', 'San José de Sisa'),
('San Martín', 'El Dorado', 'Agua Blanca'),
('San Martín', 'El Dorado', 'San Martín'),
('San Martín', 'El Dorado', 'Santa Rosa'),
('San Martín', 'El Dorado', 'Shatoja'),
('San Martín', 'Huallaga', 'Saposoa'),
('San Martín', 'Huallaga', 'Alto Saposoa'),
('San Martín', 'Huallaga', 'El Eslabón'),
('San Martín', 'Huallaga', 'Piscoyacu'),
('San Martín', 'Huallaga', 'Sacanche'),
('San Martín', 'Huallaga', 'Tingo de Saposoa'),
('San Martín', 'Lamas', 'Lamas'),
('San Martín', 'Lamas', 'Alonso de Alvarado'),
('San Martín', 'Lamas', 'Barranquita'),
('San Martín', 'Lamas', 'Caynarachi'),
('San Martín', 'Lamas', 'Cuñumbuqui'),
('San Martín', 'Lamas', 'Pinto Recodo'),
('San Martín', 'Lamas', 'Rumisapa'),
('San Martín', 'Lamas', 'San Roque de Cumbaza'),
('San Martín', 'Lamas', 'Shanao'),
('San Martín', 'Lamas', 'Tabalosos'),
('San Martín', 'Lamas', 'Zapatero'),
('San Martín', 'Mariscal Cáceres', 'Juanjuí'),
('San Martín', 'Mariscal Cáceres', 'Campanilla'),
('San Martín', 'Mariscal Cáceres', 'Huicungo'),
('San Martín', 'Mariscal Cáceres', 'Pachiza'),
('San Martín', 'Mariscal Cáceres', 'Pajarillo'),
('San Martín', 'Picota', 'Picota'),
('San Martín', 'Picota', 'Buenos Aires'),
('San Martín', 'Picota', 'Caspisapa'),
('San Martín', 'Picota', 'Pilluana'),
('San Martín', 'Picota', 'Pucacaca'),
('San Martín', 'Picota', 'San Cristóbal'),
('San Martín', 'Picota', 'San Hilarión'),
('San Martín', 'Picota', 'Shamboyacu'),
('San Martín', 'Picota', 'Tingo de Ponasa'),
('San Martín', 'Picota', 'Tres Unidos'),
('San Martín', 'Rioja', 'Rioja'),
('San Martín', 'Rioja', 'Awajun'),
('San Martín', 'Rioja', 'Elías Soplin Vargas'),
('San Martín', 'Rioja', 'Nueva Cajamarca'),
('San Martín', 'Rioja', 'Pardo Miguel'),
('San Martín', 'Rioja', 'Posic'),
('San Martín', 'Rioja', 'San Fernando'),
('San Martín', 'Rioja', 'Yorongos'),
('San Martín', 'Rioja', 'Yuracyacu'),
('San Martín', 'San Martín', 'Tarapoto'),
('San Martín', 'San Martín', 'Alberto Leveau'),
('San Martín', 'San Martín', 'Cacatachi'),
('San Martín', 'San Martín', 'Chazuta'),
('San Martín', 'San Martín', 'Chipurana'),
('San Martín', 'San Martín', 'El Porvenir'),
('San Martín', 'San Martín', 'Huimbayoc'),
('San Martín', 'San Martín', 'Juan Guerra'),
('San Martín', 'San Martín', 'La Banda de Shilcayo'),
('San Martín', 'San Martín', 'Morales'),
('San Martín', 'San Martín', 'Papaplaya'),
('San Martín', 'San Martín', 'San Antonio'),
('San Martín', 'San Martín', 'Sauce'),
('San Martín', 'San Martín', 'Shapaja'),
('San Martín', 'Tocache', 'Tocache'),
('San Martín', 'Tocache', 'Nuevo Progreso'),
('San Martín', 'Tocache', 'Polvora'),
('San Martín', 'Tocache', 'Shunte'),
('San Martín', 'Tocache', 'Uchiza'),
('Tacna', 'Tacna', 'Tacna'),
('Tacna', 'Tacna', 'Alto de la Alianza'),
('Tacna', 'Tacna', 'Calana'),
('Tacna', 'Tacna', 'Ciudad Nueva'),
('Tacna', 'Tacna', 'Inclan'),
('Tacna', 'Tacna', 'Pachia'),
('Tacna', 'Tacna', 'Palca'),
('Tacna', 'Tacna', 'Pocollay'),
('Tacna', 'Tacna', 'Sama'),
('Tacna', 'Tacna', 'Coronel Gregorio Albarracín Lanchipa'),
('Tacna', 'Candarave', 'Candarave'),
('Tacna', 'Candarave', 'Cairani'),
('Tacna', 'Candarave', 'Camilaca'),
('Tacna', 'Candarave', 'Curibaya'),
('Tacna', 'Candarave', 'Huanuara'),
('Tacna', 'Candarave', 'Quilahuani'),
('Tacna', 'Jorge Basadre', 'Locumba'),
('Tacna', 'Jorge Basadre', 'Ilabaya'),
('Tacna', 'Jorge Basadre', 'Ite'),
('Tacna', 'Tarata', 'Tarata'),
('Tacna', 'Tarata', 'Héroes Albarracín'),
('Tacna', 'Tarata', 'Estique'),
('Tacna', 'Tarata', 'Estique-Pampa'),
('Tacna', 'Tarata', 'Sitajara'),
('Tacna', 'Tarata', 'Susapaya'),
('Tacna', 'Tarata', 'Tarucachi'),
('Tacna', 'Tarata', 'Ticaco'),
('Tumbes', 'Tumbes', 'Tumbes'),
('Tumbes', 'Tumbes', 'Corrales'),
('Tumbes', 'Tumbes', 'La Cruz'),
('Tumbes', 'Tumbes', 'Pampas de Hospital'),
('Tumbes', 'Tumbes', 'San Jacinto'),
('Tumbes', 'Tumbes', 'San Juan de la Virgen'),
('Tumbes', 'Contralmirante Villar', 'Zorritos'),
('Tumbes', 'Contralmirante Villar', 'Casitas'),
('Tumbes', 'Contralmirante Villar', 'Canoas de Punta Sal'),
('Tumbes', 'Zarumilla', 'Zarumilla'),
('Tumbes', 'Zarumilla', 'Aguas Verdes'),
('Tumbes', 'Zarumilla', 'Matapalo'),
('Tumbes', 'Zarumilla', 'Papayal'),
('Ucayali', 'Coronel Portillo', 'Calleria'),
('Ucayali', 'Coronel Portillo', 'Campoverde'),
('Ucayali', 'Coronel Portillo', 'Iparia'),
('Ucayali', 'Coronel Portillo', 'Masisea'),
('Ucayali', 'Coronel Portillo', 'Yarinacocha'),
('Ucayali', 'Coronel Portillo', 'Nueva Requena'),
('Ucayali', 'Coronel Portillo', 'Manantay'),
('Ucayali', 'Atalaya', 'Raymondi'),
('Ucayali', 'Atalaya', 'Sepahua'),
('Ucayali', 'Atalaya', 'Tahuania'),
('Ucayali', 'Atalaya', 'Yurua'),
('Ucayali', 'Padre Abad', 'Padre Abad'),
('Ucayali', 'Padre Abad', 'Irazola'),
('Ucayali', 'Padre Abad', 'Curimana'),
('Ucayali', 'Padre Abad', 'Neshuya'),
('Ucayali', 'Padre Abad', 'Alexander Von Humboldt'),
('Ucayali', 'Purús', 'Purus');